testsigmahq/testsigma-docs

- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
Added new file for Troubleshooting for REST API test case failure
NOTE: written the content in HTML in view of needing the Table feature (in the markdown set up we currently have, some styling issues are there)
> Troubleshooting doc for REST API test case failure

- src/pages/docs/elements/ios-apps/supported-locator-types.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/reports/runs/rerun.md
- src/pages/docs/test-management/test-plans/overview.md
added after reviewing the previous changes
> 2.7.0 documentation - minor changes

- src/pages/docs/desired-capabilities/network-throttling.md
This article describes the steps to enable the network throttling feature using the testsigma add-on for the same.
> Documentation for network throttling using Testsigma add-on 

- src/left-nav-title.json
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/test-cases/step-types/block.md
- src/pages/docs/test-cases/step-types/step-group.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
- run tests in parallel for mobile
- edit step group support
- create block
> 2.7.1 documentation changes

- src/pages/docs/addons/create.md
- src/pages/docs/addons/pre-requisite-to-create-addon.md
- src/pages/docs/debugging/debugging-localdevices-web.md
- **Created new doc for web debugger (beta edition)**
- **Documented automatic review system for add-on**
> docs for web debugger and review system for addon

- src/pages/docs/elements/import-export.md
- src/pages/docs/elements/multiple_web_view.md
- src/pages/docs/troubleshooting/agent/unable-to-create-new-testsession.md
Created a new doc for multiple web view
> new doc for multiple webview

- src/pages/docs/agent/update-agent-manually.md
- src/pages/docs/agent/update-drivers-manually.md
- src/pages/docs/test-cases/create-steps.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
- src/pages/docs/test-cases/manage/filters.md
- src/pages/docs/test-cases/manage/import-export.md
- src/pages/docs/test-cases/manage/list-actions.md
- src/pages/docs/test-cases/overview.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/test-data/import-data-profiles.md
- src/pages/docs/test-management/test-plans/manage-test-machines.md
- src/pages/docs/test-management/test-plans/overview.md
Updated doc to reflect enhancements
https://testsigma.atlassian.net/browse/TE-459
https://testsigma.atlassian.net/browse/DOC-33
https://testsigma.atlassian.net/browse/TE-5234
https://testsigma.atlassian.net/browse/TE-5314
https://testsigma.atlassian.net/browse/DOC-77
> Sprint 3.1.1

- src/pages/docs/troubleshooting/NLPs/unable-to-capture-dropdown-element.md
Created a new doc to document the ticket https://testsigma.atlassian.net/browse/DOC-27
(unable to capture dropdown element) using select NLP.
> new troubleshooting doc unable to capture dropdown element

- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/troubleshooting/setup-issues.md
- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
Edited the below pages to document the tickets 
https://testsigma.atlassian.net/browse/DOC-23
https://testsigma.atlassian.net/browse/DOC-74
https://testsigma.atlassian.net/browse/DOC-45
- https://testsigma.com/docs/agent/setup-on-windows-mac-linux/
- https://testsigma.com/docs/agent/troubleshooting/setup-issues/
- https://testsigma.com/docs/troubleshooting/agent/mobile-device-not-displayed-recorder/
> Troubleshooting doc nov8

- src/pages/docs/desired-capabilities/app-resigning.md
- src/pages/docs/desired-capabilities/biometric-authentication.md
- src/pages/docs/desired-capabilities/network-logs.md
- src/pages/docs/desired-capabilities/screen-shot-capture.md
- src/pages/docs/desired-capabilities/webviews.md
- src/pages/docs/uploads/build-apk-or-ipa-files.md
- src/pages/docs/uploads/mobile-app-build.md
Created dummy docs for https://testsigma.atlassian.net/browse/TE-5427
> dummy docs for TE-5427

- src/components/EditButton.jsx
@PratheepV typo while creating branch name, plz ignore
> WEB-113 - Safe check github 404 link

- src/pages/docs/test-data/import-data-profiles.md
- src/pages/docs/test-data/types/environment.md
- src/pages/docs/test-data/update-test-data-profile.md
Created a new doc for bulk uploading TDP for the ticket  https://testsigma.atlassian.net/browse/TE-6040.
> created a new doc for upload TDP

- src/pages/docs/test-data/import-data-profiles.md
- src/pages/docs/test-data/update-test-data-profile.md
Updated the document https://testsigma.com/docs/test-data/import-data-profiles/ to reflect UI changes as per ticket https://testsigma.atlassian.net/browse/TE-6040
> Updated import tdp document to reflect UI changes

- src/pages/docs/elements/flutter-apps/element-identification.md
- src/pages/docs/elements/import-export.md
Created a dummy doc for the ticket https://testsigma.atlassian.net/browse/DOC-83.
> dummy doc for flutter app element identification

- src/pages/docs/elements/flutter-apps/element-identification.md
- src/pages/docs/integrations/bug-reporting/monday.com.md
Created a new doc for monday.com integration https://testsigma.atlassian.net/browse/DOC-106.
Updated flutter element identification https://testsigma.atlassian.net/browse/DOC-83.
> Testsigma monday.com integration

- src/pages/docs/faqs/web-apps/how-to-turnoff-onboarding-tutorial.md
Created a new document for https://testsigma.atlassian.net/browse/DOC-85
> Created a FAQ doc to turn off onboarding tutorial

- src/pages/docs/test-cases/cross-application-testing.md
- src/pages/docs/test-data/add-values-to-test-data-profile.md
Added docs for NLP's https://testsigma.atlassian.net/browse/DOC-87 and https://testsigma.atlassian.net/browse/DOC-88. Please review and update.
> Added NLP docs

- src/pages/docs/test-cases/manage/import-export.md
- src/pages/docs/test-data/bulk-deletion-of-test-data-profile.md
Added bulk deletion doc for https://testsigma.atlassian.net/browse/DOC-63 and updated imports and exports doc for https://testsigma.atlassian.net/browse/DOC-21.
> Added bulk deletion and updated imports & exports

- src/pages/docs/api/upload-and-update-test-data-profile.md
- src/pages/docs/test-cases/manage/import-export.md
Created a new document for https://testsigma.atlassian.net/browse/DOC-92. Also updated content for import and export test cases.
> Created doc for uploading & updating TDP using APIs

- src/pages/docs/desired-capabilities/screen-shot-capture.md
- src/pages/docs/desired-capabilities/webviews.md
Updated content for Screenshot capture & WebViews to document ticket https://testsigma.atlassian.net/browse/TE-5427. Please review.
> Updated content for Screenshot capture & WebViews

- src/pages/docs/desired-capabilities/app-resigning.md
- src/pages/docs/uploads/build-apk-or-ipa-files.md
Updated enabling resigning app & mobile build docs for https://testsigma.atlassian.net/browse/TE-5427 ticket. Please review.
> Updated enabling resigning app & mobile build docs

- src/pages/docs/desired-capabilities/more-prerequisite-settings.md
Adding a document for more settings under desired capabilities for the ticket https://testsigma.atlassian.net/browse/TE-5427.
> Adding a document for more settings.

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
Created a document for https://testsigma.atlassian.net/browse/DOC-114. Please review.
> Created a new doc to schedule test plan using API

- src/pages/docs/collaboration/deleting-users-from-a-project.md
- src/pages/docs/collaboration/invite-team-members.md
Updated adding users & Added a document for deleting users for ticket https://testsigma.atlassian.net/browse/DOC-115. Please review.
> Adding and deleting users

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
Updated content and made changes to the doc as per suggestions for https://testsigma.atlassian.net/browse/DOC-114. Please review.
> Update & Delete content for scheduling test plan

- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/troubleshooting/setup-issues.md
- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/collaboration/deleting-users-from-a-project.md
- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/desired-capabilities/most-common.md
- src/pages/docs/elements/web-apps/supported-locator-types.md
- src/pages/docs/troubleshooting/agent/unable-to-create-new-testsession.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-UI.md
Fixed 404 errors in docs page
404-Error-Fix 
404-Error-fix2
> 404- Error page fix

- src/pages/docs/test-management/test-plans/disable-test-cases-in-test-plans.md
Created a new document for https://testsigma.atlassian.net/browse/DOC-65. Please review.
> Created doc for disabling test cases in a test plan

- src/pages/docs/test-cases/manage/import-from-yaml-or-git.md
- src/pages/docs/test-management/test-plans/after-test.md
Created new documents for After Test block and Importing Test Cases via YAML/GIT for tickets https://testsigma.atlassian.net/browse/DOC-107 & https://testsigma.atlassian.net/browse/DOC-120. Please review.
> New docs for importing yaml file & after test.

- src/pages/docs/api/examples/update-test-case-results-using-API.md
- src/pages/docs/test-cases/manage/update-test-case-results-in-a-test-plan.md
Created new docs for updating test case results using UI & API for the ticket https://testsigma.atlassian.net/browse/DOC-102. Please review.
> Created docs for updating test results by UI & API

- src/pages/docs/api/examples/update-test-case-results-using-API.md
- src/pages/docs/test-cases/manage/update-test-case-results-in-a-test-plan.md
Created a new document for updating test results by UI and API for doc https://testsigma.atlassian.net/browse/DOC-102. Please review.
> Created docs for updating test results by UI & API (Doc 102)

- src/pages/docs/test-cases/step-types/nested-groups.md
Created a new document for the ticket https://testsigma.atlassian.net/browse/DOC-113.
> created a new document for nested step groups

- src/pages/docs/addons/create-a-post-plan-hook-add-on.md
Created a new doc for https://testsigma.atlassian.net/browse/DOC-108 post plan hook addon.
[DOC-108]: https://testsigma.atlassian.net/browse/DOC-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Post plan hook addon

- src/pages/docs/addons/create-a-post-plan-hook-add-on.md
- src/pages/docs/test-management/test-plans/post-plan-hook.md
Created a new document for post plan hook and post plan hook addon
> Post Plan Hook and Post Plan Hook addon

- src/components/layout.scss
- src/components/seo.jsx
- src/pages/docs/addons/create-a-post-plan-hook-add-on.md
- src/pages/docs/test-cases/step-types/nested-groups.md
- src/pages/docs/test-management/test-plans/post-plan-hook.md
Created new documents for Post plan hook & Nested steps groups.
> Main Site PR

- src/pages/docs/integrations/bug-reporting/azuredevops.md
Created a document for the ticket https://testsigma.atlassian.net/browse/DOC-121. Please Review.
> Created document for Azure DevOps integration.

- src/pages/docs/integrations/bug-reporting/azuredevops.md
Divesh has approved this Azure DevOps integration document. Please merge it to the main.
> Created document for Azure DevOps integration. (#113)

- src/pages/docs/desired-capabilities/incognito-mode.md
Created a new doc for desired capabilities, and run the browser in incognito or private mode for ticket https://testsigma.atlassian.net/browse/DOC-122.
> Run the browser in incognito or private mode.

- .github/workflows/staging-cd.yml
- src/environment.ts
- src/pages/docs/desired-capabilities/incognito-mode.md
- src/templates/page.jsx
Divesh has approved this desired capability: running the browser in incognito or private mode document. Please merge it into the main.
> Created a new doc for desired capability: running the browser in incognito or private mode 

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/test-cases/manage/import-from-yaml-or-git.md
Updated an Image in Import from YAML/GIT doc and updated Request and response body details in Schedule, Update and Delete a test plan using API doc for ticket https://testsigma.atlassian.net/browse/DOC-126.
> Updated Imports doc & Schedule Test Plans with API

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/test-cases/manage/import-from-yaml-or-git.md
Both of the updated docs (Import from YAML/GIT doc and updated Request and response body details) are approved. Please review.
> updated imports doc & schedule Testplans with API (#118)

- src/pages/docs/api/restful-api-testing-version-2/add-body-data.md
- src/pages/docs/api/restful-api-testing-version-2/add-restful-api-in-test-steps.md
- src/pages/docs/api/restful-api-testing-version-2/adding-parameters.md
- src/pages/docs/api/restful-api-testing-version-2/api-request.md
- src/pages/docs/api/restful-api-testing-version-2/attachments-rest-api.md
- src/pages/docs/api/restful-api-testing-version-2/authorization-request.md
- src/pages/docs/api/restful-api-testing-version-2/headers-in-api-request.md
- src/pages/docs/api/restful-api-testing-version-2/stored-objects.md
- src/pages/docs/api/restful-api-testing-version-2/stored-variables-in-restful-api.md
- src/pages/docs/api/restful-api-testing-version-2/verifications-request.md
- src/pages/docs/test-cases/step-types/rest-api.md
For the ticket https://testsigma.atlassian.net/browse/DOC-104, created a new document for the RESTful API. 
> RESTful API.

- src/pages/docs/api/restful-api-testing-version-2/stored-variables-in-restful-api.md
- src/pages/docs/api/restful-api-testing-version-2/verifications-request.md
- src/pages/docs/desired-capabilities/incognito-mode.md
Content for the RESTful API has been updated, and gifs have been added for https://testsigma.atlassian.net/browse/DOC-104 and https://github.com/testsigmahq/testsigma-docs/pull/117#issue-1536274723. 
> Updated Content for RESTful API and Added gifs

- src/pages/docs/getting-started/setup/downloadable-package.md
Updated existing Testsigma Setup document as per the ticket https://testsigma.atlassian.net/browse/TOS-970. Please review.
> Updated existing doc as per the comments.

- src/pages/docs/test-cases/create-steps-recorder/web-apps/record-steps-in-middle.md
Created a new document for recording steps anywhere in a Test Case. Please review
> Created a new doc for recording steps in middle

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/api/examples/update-test-case-results-using-API.md
Response to comments on tickets https://testsigma.atlassian.net/browse/DOC-131 and https://testsigma.atlassian.net/browse/DOC-132, updated the API examples in the documentation. Please review.
> Updated API examples

- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/api/examples/update-test-case-results-using-API.md
- src/pages/docs/continuous-integration/shell-script.md
- src/pages/docs/getting-started/setup/downloadable-package.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/record-steps-in-middle.md
Sam approved the document on API examples. Check and merge it into the main branch.
> Merge updated API examples to the main branch.

- src/pages/docs/runs/test-plan-executions.md
- src/pages/docs/test-management/test-plans/after-test-suite.md
Created a new document for AfterTest Suite and updated the Test Plan executions document for the tickets https://testsigma.atlassian.net/browse/DOC-116 & https://testsigma.atlassian.net/browse/DOC-125. Please review.
> New doc for AfterTest Suite & updated TP results

- src/pages/docs/runs/test-plan-executions.md
- src/pages/docs/test-management/test-plans/after-test-suite.md
Divesh reviewed and approved both documents. Please merge it to the main.
> New doc for AfterTest Suite & updated TP results (#132)

- src/pages/docs/visual-testing/configure-test-cases.md
Created a new document for configuring Visual testing in Test cases.
> Doc for configuring Visual testing in Test cases

- src/pages/docs/visual-testing/configure-test-cases.md
Divesh approved the document. Please merge it to the main.
> Doc for configuring Visual testing in Test cases (#134)

- src/pages/docs/test-management/test-plans/email-configuration.md
Created a new document for email configuration in the test plan for the ticket: https://testsigma.atlassian.net/browse/DOC-136
> Email configuration in Test Plan.

- src/pages/docs/test-management/test-plans/email-configuration.md
Amit Savyasachi approved the document. Please merge it to the main.
> Document for email configuration in test plan. (#136)

- src/pages/docs/desired-capabilities/most-common.md
Updated Desired Capabilities doc to add to Disable Chrome alert notifications for the ticket https://testsigma.atlassian.net/browse/DOC-82. Please review.
> Updated capabilities doc to disable chrome alerts

- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-test-recorder.md
Updated Failed to Start Mobile Test Recorder document for the ticket: https://testsigma.atlassian.net/browse/DOC-118.
> Updated Failed to Start Mobile Test Recorder doc

- src/pages/docs/desired-capabilities/most-common.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-test-recorder.md
Amit Savyasachi approved the document. Please merge it to the main.
> Doc for Failed to Start Mobile Test Recorder

- src/pages/docs/api/environments.md
- src/pages/docs/test-data/create-environment-data.md
- src/pages/docs/test-data/types/environment.md
Updated Environment Test Data document for the ticket: https://testsigma.atlassian.net/browse/DOC-97.
> Updated Environment TD Doc

- src/pages/docs/test-data/create-environment-data.md
Added GIF to the Create Environment Data document for ticket: https://testsigma.atlassian.net/browse/DOC-97
> Added GIF to the Create Environment Data document.

- src/pages/docs/agent/setup-on-windows-mac-linux.md
Update Run Testsigma Agent Using Docker the ticket's documentation for: https://testsigma.atlassian.net/browse/DOC-146.
> Updated Agent using Docker Doc

- src/pages/docs/api/restful-api-testing-version-2/authorization-request.md
- src/pages/docs/reports/runs/export-report-junit.md
- src/pages/docs/reports/runs/export-report-pdf.md
- src/pages/docs/reports/runs/export-report-xls.md
- src/pages/docs/reports/runs/test-case-reports.md
- src/pages/docs/reports/runs/test-suite-reports.md
Updated Analytics and Reports doc & API Authorization doc as per the tickets https://testsigma.atlassian.net/browse/DOC-141 & https://testsigma.atlassian.net/browse/DOC-137. Also updated a few docs to maintain uniformity. Please review.
> Updated reports doc and API auth doc.

- src/pages/docs/test-cases/create-steps-nl/step-settings.md
Added Test Step Retries doc as per the tickets https://testsigma.atlassian.net/browse/DOC-130 Please review.
> Added Test Step Retries Document

- src/pages/docs/getting-started/setup/downloadable-package.md
- src/pages/docs/test-cases/create-steps-nl/step-settings.md
Upadted Test Step Setting document as per the tickets https://testsigma.atlassian.net/browse/DOC-130. Please review.
> Updated Test Step Setting Documents

- src/pages/docs/api/restful-api-testing-version-2/api-request.md
- src/pages/docs/getting-started/setup/downloadable-package.md
- src/pages/docs/test-cases/create-steps-nl/step-settings.md
Himani approved the document. Please merge it to the main.
> Merge Unicode & Test Step Details Doc

- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/api/examples/values-of-test-data-profile.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
Updated docs as per the following tickets:
https://testsigma.atlassian.net/browse/DOC-40
https://testsigma.atlassian.net/browse/DOC-2
https://testsigma.atlassian.net/browse/DOC-53
https://testsigma.atlassian.net/browse/DOC-61
Please review.
> Updated 4 docs as per Docs-2,40,53&61.

- src/pages/docs/api/examples/values-of-test-data-profile.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/getting-started/introduction-community.md
I've updated the intro docs according to the ticket https://testsigma.atlassian.net/browse/DOC-119. Please review.
> Edited intro docs by replacing with a new video.

- src/left-nav-title.json
- src/pages/docs/continuous-integration/gitlab-cicd.md
- src/pages/docs/troubleshooting/NLPs/unable-to-select-radiobutton.md
- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
- src/pages/docs/troubleshooting/setup/server-docker-deployment-errors.md
- src/pages/docs/troubleshooting/web-apps/test-execution-queued-for-a-long-time.md
- src/pages/docs/troubleshooting/web-apps/url-not-accessible.md
- src/pages/docs/uploads/upload-apps.md
- src/pages/docs/uploads/upload-files.md
- src/pages/docs/visual-testing/configure-test-steps.md
- src/pages/docs/visual-testing/update-baseline.md
- src/pages/docs/visual-testing/view-debug-results.md
Created a new doc for the ticket - https://testsigma.atlassian.net/browse/DOC-42
Updated 10 meta descriptions for the ticket - https://testsigma.atlassian.net/browse/MAR-175
Please review.
> Created new document for GitLab integration, updated meta descriptions for 10 docs & left nav title change. 

- src/left-nav-title.json
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/api/examples/values-of-test-data-profile.md
- src/pages/docs/continuous-integration/gitlab-cicd.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/getting-started/introduction-community.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
- src/pages/docs/troubleshooting/NLPs/unable-to-select-radiobutton.md
- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
- src/pages/docs/troubleshooting/setup/server-docker-deployment-errors.md
- src/pages/docs/troubleshooting/web-apps/test-execution-queued-for-a-long-time.md
- src/pages/docs/troubleshooting/web-apps/url-not-accessible.md
- src/pages/docs/uploads/upload-apps.md
- src/pages/docs/uploads/upload-files.md
- src/pages/docs/visual-testing/configure-test-steps.md
- src/pages/docs/visual-testing/update-baseline.md
- src/pages/docs/visual-testing/view-debug-results.md
The respective reporters approved all the docs. Please merge it to the main.
> The docs are approved. Please merge it to the main. 

- src/pages/docs/test-cases/create-steps-restapi/verifications-request.md
Added Before invoking API, VerificationTypes in Verification  RESTful API Document for the ticket - https://testsigma.atlassian.net/browse/DOC-151.
> Updated Verification RESTful API Document

- src/pages/docs/api/examples/trigger-multiple-test-plans.md
- src/pages/docs/test-cases/step-types/step-group.md
- src/pages/docs/test-step-recorder/install-chrome-extension.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
- src/pages/docs/troubleshooting/NLPs/unable-to-click-checkbox.md
- src/pages/docs/troubleshooting/NLPs/unable-to-retrieve-value.md
- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
- src/pages/docs/troubleshooting/agent/unable-to-create-new-testsession.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-UI.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-test-recorder.md
- src/pages/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures.md
- src/pages/docs/troubleshooting/mobile-apps/test-execution-queued-for-a-long-time.md
Updated Step Groups, Rest APIs & Meta descriptions as per the following tickets - 
https://testsigma.atlassian.net/browse/DOC-157
https://testsigma.atlassian.net/browse/DOC-36
https://testsigma.atlassian.net/browse/MAR-175
Please review.
> Updated Step Groups, Rest APIs & Meta descriptions

- src/pages/docs/api/examples/trigger-multiple-test-plans.md
- src/pages/docs/test-cases/create-steps-restapi/verifications-request.md
- src/pages/docs/test-cases/step-types/step-group.md
- src/pages/docs/test-step-recorder/install-chrome-extension.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
- src/pages/docs/troubleshooting/NLPs/unable-to-click-checkbox.md
- src/pages/docs/troubleshooting/NLPs/unable-to-retrieve-value.md
- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
- src/pages/docs/troubleshooting/agent/unable-to-create-new-testsession.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-UI.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-test-recorder.md
- src/pages/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures.md
- src/pages/docs/troubleshooting/mobile-apps/test-execution-queued-for-a-long-time.md
Himani has approved the VerificationTypes, Before Invoking API in the Verification RESTful API Document for the ticket - https://testsigma.atlassian.net/browse/DOC-151. Kindly proceed with merging the said document to the main branch. Thank you.
> Merge Verfication RESTful API Document 

- src/pages/docs/getting-started/testsigma-sample-apps.md
Created document for Testsigma Sample Applications as per the ticket https://testsigma.atlassian.net/browse/DOC-144. Please review.
> Created a new document for sample apps.

- src/pages/docs/elements/web-apps/verify-elements.md
I created a new document for verifying elements in Chrome DevTools according to the ticket https://testsigma.atlassian.net/browse/DOC-117. Please review.
> Created a new doc for verifying elements

- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/projects/versions.md
Updated Versions document as per new UI updates for the ticket https://testsigma.atlassian.net/browse/DOC-145. Please review.
> Updated Versions doc as per new UI updates. 

- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/on-premise setup/prerequisites.md
Created a new doc for the ticket https://testsigma.atlassian.net/browse/DOC-148. Please review.
> Created a new document for On-prem prerequisites.

- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/on-premise setup/prerequisites.md
- src/pages/docs/on-premise setup/sla.md
Created a new doc for Service Level Agreement (SLA) for the customer according to the ticket - https://testsigma.atlassian.net/browse/DOC-149. Please review.
> Created new document for SLA for customers. 

- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/on-premise setup/post-installation-checklist.md
Created a new document for the post-installation checklist for on-premise setup as per the ticket - https://testsigma.atlassian.net/browse/DOC-158. Please review.
> Created a new doc for post-installation checklist

- src/pages/docs/api/examples/rerun-test-cases-in-test-run.md
- src/pages/docs/configuration/security/azure-sso.md
- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/reports/runs/rerun.md
Created a new document for Rerun Test Cases using API & updated the rerun doc with updated UI as per the ticket https://testsigma.atlassian.net/browse/DOC-152. Please review.
> Created new doc for Rerun using API & updated rerun doc as per new UI. 

- src/pages/docs/desired-capabilities/most-common.md
- src/pages/docs/test-data/data-generators/default-list.md
- src/pages/docs/test-data/types/mailbox.md
Added inputs and examples for Mailbox Alias and Default Test Data Generators, and Also added Desired Capabilities for Chrome and hyperlinked all headings.
> Updated Default TDG, Mailbox TDT, Desired Capabilities Doc

- src/pages/docs/test-cases/manage/import-postman-to-testsigma.md
- src/pages/docs/test-cases/manage/update-test-case-results-in-a-test-plan.md
New Document Import Postman's Collections and Environments were added for the tickets https://testsigma.atlassian.net/browse/DOC-138.
> Doc Import Postman's Collections and Environments

- src/pages/docs/test-cases/manage/import-postman-to-testsigma.md
Added Export Postman Data Dump in Import Postman's Collections and Environments were added for the tickets https://testsigma.atlassian.net/browse/DOC-138.
> Added Postman Data Dump Section

- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/contributing/testsigma-development-environment/macos-and-intellij-ue.md
Created new doc for Testsigma Development Environment setup in macOS and IntelliJ Ultimate Edition as per the ticket https://testsigma.atlassian.net/browse/DOC-166 & made few changes as per https://testsigma.atlassian.net/browse/DOC-168. Please review.
> Created new doc for dev env setup in macOS

- src/pages/docs/test-data/types/concat.md
Made few more changes as per the feedback for the doc https://testsigma.atlassian.net/browse/DOC-154. Please review.
> Updated concat test data document

- src/pages/docs/addons/update.md
Updated the updating addons doc as per the ticket - https://testsigma.atlassian.net/browse/DOC-17. Please review.
> Updated addons doc

- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-cases/step-types/while-loop.md
Updated If condition & while loop docs as per the ticket https://testsigma.atlassian.net/browse/DOC-80. Please review.
> Updated If condition & While loop docs.

- src/pages/docs/test-data/data-generators/default-list.md
Default test data generators have been updated and categorised for better organisation and efficiency, and custom calculations have been added to the tickets. https://testsigma.atlassian.net/browse/DOC-134; https://testsigma.atlassian.net/browse/DOC-5; https://testsigma.atlassian.net/browse/DOC-153.
> Updated default test data generators by category

- src/pages/docs/integrations/collaboration/slack.md
Updated Slack Integration doc page as per the ticket https://testsigma.atlassian.net/browse/DOC-68. Please review.
> Updated slack integration doc page.

- src/pages/docs/integrations/collaboration/slack.md
- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-data/data-generators/default-list.md
Divesh has approved the ticket's Default Test Data Generators Document - https://testsigma.atlassian.net/browse/DOC-134; https://testsigma.atlassian.net/browse/DOC-5; https://testsigma.atlassian.net/browse/DOC-153. Please go ahead and merge the document to the main branch. Thank you.
> Merge Default Test Data Generators Document

- src/pages/docs/continuous-integration/github-cicd.md
- src/pages/docs/reports/runs/export-report-pdf.md
Updated Export PDF report document as per the ticket https://testsigma.atlassian.net/browse/DOC-161. Please review.
> Updated Export PDF report doc

- src/pages/docs/reports/export-reports/export-report-pdf.md
- src/pages/docs/reports/export-reports/export-report-xls.md
- src/pages/docs/reports/export-reports/export-reports-junit.md
Added new folder for exporting reports in JUnit/XLS/PDF formats. Please review.
> Added new folder for exporting reports

- src/pages/docs/troubleshooting/mobile-apps/unable-to-start-wda-process.md
Created a new documentation for troubleshooting "Unable to start WDA Process on iPhone" issue as per the ticket https://testsigma.atlassian.net/browse/DOC-3. Please review.
> Created a new doc for troubleshooting an issue.

- src/pages/docs/continuous-integration/github-cicd.md
- src/pages/docs/reports/export-reports/export-report-pdf.md
- src/pages/docs/reports/export-reports/export-report-xls.md
- src/pages/docs/reports/export-reports/export-reports-junit.md
- src/pages/docs/reports/runs/export-report-pdf.md
- src/pages/docs/troubleshooting/mobile-apps/unable-to-start-wda-process.md
Updated PDF export doc & created a new doc for troubleshooting an issue as per the tickets https://testsigma.atlassian.net/browse/DOC-161 & https://testsigma.atlassian.net/browse/DOC-3. Submitting this PF to merge it to main since they are reviewed & approved.
> Updated PDF export doc & created a new doc for troubleshooting an issue. 

- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/getting-started/introduction-community.md
- src/pages/docs/getting-started/setup/overview.md
- src/templates/page.jsx
Revert 301 redirection issue fix change as we have an index page for DOCs.
> WEB-313 - Reverting 310 redirection issue fix change

- src/pages/docs/test-data/types/environment.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-data/types/overview.md
- src/pages/docs/test-data/types/parameter.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/test-data/types/random.md
- src/pages/docs/test-data/types/raw.md
- src/pages/docs/test-data/types/runtime.md
- src/pages/docs/test-management/test-plans/cross-browser-testing.md
- src/pages/docs/test-management/test-plans/distributed-testing.md
- src/pages/docs/test-management/test-plans/headless-testing.md
- src/pages/docs/test-management/test-plans/manage-test-machines.md
- src/pages/docs/test-management/test-plans/manage-test-suites.md
- src/pages/docs/test-management/test-plans/overview.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
- src/pages/docs/test-management/test-plans/schedule-plans.md
- src/pages/docs/test-management/test-plans/supported-test-lab-types.md
- src/pages/docs/test-management/test-suites/overview.md
Updated meta descriptions for 18 documents as part of SEO best practices.
> Updated meta descriptions for 18 documents

- src/pages/docs/addons/Faqs/connect-mongodb-and-postgresql-via-addon.md
Created a new document on how to connect MongoDB & PostgreSQL Database for the ticket https://testsigma.atlassian.net/browse/DOC-128.
> Connect MongoDB & PostgreSQL Database

- src/pages/docs/addons/Faqs/connect-mongodb-and-postgresql-via-addon.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/getting-started/introduction-community.md
- src/pages/docs/getting-started/setup/overview.md
- src/pages/docs/test-data/types/environment.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-data/types/overview.md
- src/pages/docs/test-data/types/parameter.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/test-data/types/random.md
- src/pages/docs/test-data/types/raw.md
- src/pages/docs/test-data/types/runtime.md
- src/pages/docs/test-management/test-plans/cross-browser-testing.md
- src/pages/docs/test-management/test-plans/distributed-testing.md
- src/pages/docs/test-management/test-plans/headless-testing.md
- src/pages/docs/test-management/test-plans/manage-test-machines.md
- src/pages/docs/test-management/test-plans/manage-test-suites.md
- src/pages/docs/test-management/test-plans/overview.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
- src/pages/docs/test-management/test-plans/schedule-plans.md
- src/pages/docs/test-management/test-plans/supported-test-lab-types.md
- src/pages/docs/test-management/test-suites/overview.md
- src/templates/page.jsx
Divesh approved the connection of MongoDB and PostgreSQL database documents for ticket https://testsigma.atlassian.net/browse/DOC-128. Please go ahead and merge the document into the main branch. Thank you.
> Merge Connect MongoDB & PostgreSQL Database Doc

- src/pages/docs/addons/ocr-extraction.md
- src/pages/docs/continuous-integration/circle-ci.md
- src/pages/docs/getting-started/setup/testsigma-cloud.md
- src/pages/docs/runs/test-plan-executions.md
- src/pages/docs/test-data/types/runtime.md
Updated Runtime Variable, Test plan executions, Circle CI and added a new doc for OCR Text Extraction Addon.
> Updated Runtime, Test plan executions docs.

- src/pages/docs/addons/community-marketplace.md
- src/pages/docs/addons/create-a-post-plan-hook-add-on.md
- src/pages/docs/addons/create.md
- src/pages/docs/addons/install-community-addon.md
- src/pages/docs/addons/ocr-extraction.md
- src/pages/docs/addons/pre-requisite-to-create-addon.md
- src/pages/docs/addons/types.md
- src/pages/docs/addons/update.md
- src/pages/docs/addons/what-is-an-addon.md
Updated OCR Text Extraction Addon doc and updated meta descriptions for all addon doc pages.
> Updated OCR Text Extraction doc.

- src/pages/docs/projects/overview.md
Added Switching Projects section. And Updated the Screenshot and Changed the Content for the ticket https://testsigma.atlassian.net/browse/DOC-47.
> Updated Manage Projects Document

- src/pages/docs/FAQs/web-apps/how-to-turnoff-onboarding-tutorial.md
- src/pages/docs/FAQs/web-apps/why-chrome-extension.md
- src/pages/docs/FAQs/web-apps/why-cloud-devices-cannot-access-local-apps.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/sdk/manage-parameter-test-data.md
- Added a new document for simulating the pressing of non-text keys in Test Cases as per the document https://testsigma.atlassian.net/browse/DOC-58.
- Updated meta descriptions for all docs under FAQs section.
> Added a new doc for Non-text key values & usage.

- src/pages/docs/FAQs/web-apps/how-to-turnoff-onboarding-tutorial.md
- src/pages/docs/FAQs/web-apps/why-chrome-extension.md
- src/pages/docs/FAQs/web-apps/why-cloud-devices-cannot-access-local-apps.md
- src/pages/docs/addons/community-marketplace.md
- src/pages/docs/addons/create-a-post-plan-hook-add-on.md
- src/pages/docs/addons/create.md
- src/pages/docs/addons/install-community-addon.md
- src/pages/docs/addons/ocr-extraction.md
- src/pages/docs/addons/pre-requisite-to-create-addon.md
- src/pages/docs/addons/types.md
- src/pages/docs/addons/update.md
- src/pages/docs/addons/what-is-an-addon.md
- src/pages/docs/continuous-integration/circle-ci.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/getting-started/setup/testsigma-cloud.md
- src/pages/docs/projects/overview.md
- src/pages/docs/runs/test-plan-executions.md
- src/pages/docs/sdk/manage-parameter-test-data.md
- src/pages/docs/test-data/types/runtime.md
Added a new document for Non-text key values and updated OCR text extraction, Runtime, & Test Execution docs. 
Docs are reviewed & Approved. Please merge it to main site.
> New doc for non-text key values & updated OCR doc. 

- src/pages/docs/configuration/api-keys.md
- src/pages/docs/configuration/ios-settings.md
- src/pages/docs/configuration/reset-password.md
- src/pages/docs/configuration/security/azure-sso.md
- src/pages/docs/configuration/security/google-sso.md
- src/pages/docs/configuration/security/okta-sso.md
- src/pages/docs/configuration/security/overview.md
- src/pages/docs/configuration/storage-types.md
Updated images, URLs in **okta SSO** document and updated meta descriptions for all the documents under **Configuration**.
> Updated images & URLs in okta SSO document

- src/pages/docs/api/upload-files.md
- src/pages/docs/test-data/data-generators/default-list.md
Updated Response and Request Body for Upload File API and Update New file API. Added Response & Request Fields for all sections for ticket https://testsigma.atlassian.net/browse/DOC-177. 
Added New Data Generators for Mail Box Function.
> Updated Upload files using API Document

- src/components/navcards.jsx
- Added Best practice widget
- Changed the inner link of On-premises setup
> WEB-405 - Added Best practice widget and changed inner link of On premises setup

- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ce.md
- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ue.md
- src/pages/docs/contributing/open-source-dev-environment-setup/windows-and-intelliJ-ue.md
- src/pages/docs/reports/dashboard.md
Updated all 3 docs under Testsigma Dev Env Setup section as per the ticket https://testsigma.atlassian.net/browse/DOC-182.
> Updated Testsigma dev env setup docs.

- src/pages/docs/reports/export-reports/export-reports-junit.md
- src/pages/docs/reports/runs/drill-down-reports.md
- src/pages/docs/reports/runs/filter-custom-reports.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/reports/runs/rerun.md
- src/pages/docs/reports/runs/test-case-reports.md
- src/pages/docs/reports/runs/test-machine-reports.md
- src/pages/docs/reports/runs/test-suite-reports.md
Updated 404 interlinks in the docs as per the ticket https://testsigma.atlassian.net/browse/DOC-183. Please review.
> Updated 404 interlinks in the documents.

- src/pages/docs/addons/create.md
- src/pages/docs/addons/install-community-addon.md
- src/pages/docs/integrations/collaboration/google-chat.md
- src/pages/docs/reports/dashboard.md
- src/pages/docs/reports/runs/test-case-reports.md
- src/pages/docs/reports/runs/test-machine-reports.md
- src/pages/docs/reports/runs/test-suite-reports.md
- src/pages/docs/runs/adhoc-runs.md
- src/pages/docs/runs/dry-runs-on-local-devices.md
- src/pages/docs/runs/run-on-cloud-vendor-platforms.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/visual-testing/update-baseline.md
- src/pages/docs/visual-testing/view-debug-results.md
Created & replaced big GIFs with new GIFs & Updated metas for the docs. Please review.
> Added GIFs & updated metas for all the docs

- src/pages/docs/addons/create.md
- src/pages/docs/addons/install-community-addon.md
- src/pages/docs/api/upload-files.md
- src/pages/docs/configuration/ios-settings.md
- src/pages/docs/integrations/collaboration/google-chat.md
- src/pages/docs/reports/dashboard.md
- src/pages/docs/reports/runs/test-case-reports.md
- src/pages/docs/reports/runs/test-machine-reports.md
- src/pages/docs/reports/runs/test-suite-reports.md
- src/pages/docs/runs/adhoc-runs.md
- src/pages/docs/runs/dry-runs-on-local-devices.md
- src/pages/docs/runs/run-on-cloud-vendor-platforms.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/troubleshooting/REST-API/troubleshooting-API testcase-failure.md
- src/pages/docs/visual-testing/update-baseline.md
- src/pages/docs/visual-testing/view-debug-results.md
Himani approved the iOS Native Settings documents for the ticket https://testsigma.atlassian.net/browse/DOC-75. Please go ahead and merge the document into the main branch. Thank you.
> Merge iOS Native Settings Document

- src/pages/docs/addons/community-marketplace.md
- src/pages/docs/addons/update.md
- src/pages/docs/addons/what-is-an-addon.md
- src/pages/docs/integrations/collaboration/google-chat.md
- src/pages/docs/integrations/collaboration/microsoft-teams.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/runs/dry-runs-on-local-devices.md
- src/pages/docs/runs/run-on-cloud-vendor-platforms.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/test-data/overview.md
- src/pages/docs/test-data/types/data-generator.md
- src/pages/docs/test-data/types/parameter.md
- src/pages/docs/visual-testing/view-debug-results.md
Created & replaced big GIFs with new GIFs & Updated Metas for the docs. Please review.
> Updated GIFs & Metas in the following docs

- src/pages/docs/addons/community-marketplace.md
- src/pages/docs/addons/update.md
- src/pages/docs/addons/what-is-an-addon.md
- src/pages/docs/integrations/collaboration/google-chat.md
- src/pages/docs/integrations/collaboration/microsoft-teams.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/runs/dry-runs-on-local-devices.md
- src/pages/docs/runs/run-on-cloud-vendor-platforms.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/test-data/overview.md
- src/pages/docs/test-data/types/data-generator.md
- src/pages/docs/test-data/types/parameter.md
- src/pages/docs/visual-testing/view-debug-results.md
Created & replaced big GIFs with new GIFs & Updated Metas for the docs. Please review.
> Updated GIFs & Metas in the following docs (#219)

- src/pages/docs/on-premise setup/post-installation-checklist.md
- src/pages/docs/on-premise setup/setup.md
- src/pages/docs/troubleshooting/on-prem/restart-docker.md
Added a new doc for On-prem troubleshooting issue & updated Setup & Checklist pages. as per the ticket https://testsigma.atlassian.net/browse/DOC-186. Please review.
> Added new doc for On-prem troubleshooting

- src/pages/docs/on-premise setup/install-docker-on-uzure-infra.md
Created a new document for installing Docker on a Unix-based OS within Azure infrastructure as per the ticket https://testsigma.atlassian.net/browse/DOC-172. Please review.
> Added new doc for installing Docker on Azure infra

- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/debugging/launch-the-debugger-in-the-same-window.md
- src/pages/docs/on-premise setup/install-docker-on-uzure-infra.md
Created new document for launching debugger in the same window as per the ticket https://testsigma.atlassian.net/browse/TE-8632. Please review
> Created new doc to launch debugger in same window

- src/pages/docs/test-cases/manage/add-edit-delete.md
The Manage Test Cases Document URL has been reverted to its original state and updated Meta Description.
SEO checklist
Meta Title Should have 60 Characters - ✅ 
@bharathk08
> Updated Manage Test Cases Document

- src/components/Footer.scss
- src/components/SubscribeButton.jsx
Moved product subscription form to HubSpot form on docs
> WEB-375 - Moved product subscription form to HubSpot form on docs

- src/pages/docs/test-management/test-plans/partial-test-plan-run-via-api.md
Created a new document for executing a partial test plan run via API for the ticket https://testsigma.atlassian.net/browse/DOC-169.
SEO Checklist:
Meta Title Should have 60 Characters - ✅ 
@bharathk08
> Created Execute Partial Test Plan Run via API Doc

- src/pages/docs/desired-capabilities/network-logs.md
Added a new "Enable Network Logs in Test Plan" section to the Network Logs for the ticket https://testsigma.atlassian.net/browse/DOC-190.
SEO checklist
Meta Title Should have 60 Characters - ✅ 
@bharathk08
> Updated Network Logs Document

- src/pages/docs/elements/android-apps/capture-single-element.md
- src/pages/docs/elements/android-apps/create-manually.md
- src/pages/docs/elements/android-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/android-apps/overview.md
- src/pages/docs/elements/android-apps/record-multiple-elements.md
- src/pages/docs/elements/android-apps/supported-locator-types.md
- src/pages/docs/elements/desktop-windows/record-elements.md
- src/pages/docs/elements/dynamic-elements/with-environment-data.md
- src/pages/docs/elements/dynamic-elements/with-parameter-test-data.md
- src/pages/docs/elements/dynamic-elements/with-runtime-test-data.md
- src/pages/docs/elements/flutter-apps/element-identification.md
- src/pages/docs/elements/import-export.md
- src/pages/docs/elements/ios-apps/capture-single-element.md
- src/pages/docs/elements/ios-apps/create-manually.md
- src/pages/docs/elements/ios-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/ios-apps/overview.md
- src/pages/docs/elements/ios-apps/record-multiple-elements.md
- src/pages/docs/elements/ios-apps/supported-locator-types.md
- src/pages/docs/elements/mobile-web-application/create-manually.md
- src/pages/docs/elements/mobile-web-application/record-elements.md
- src/pages/docs/elements/overview.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/elements/web-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/web-apps/overview.md
- src/pages/docs/elements/web-apps/record-multiple-elements.md
- src/pages/docs/elements/web-apps/shadow-dom.md
- src/pages/docs/elements/web-apps/supported-locator-types.md
- src/pages/docs/elements/web-apps/verify-elements.md
- src/pages/docs/test-cases/manage/add-test-cases-for-mobile-web-app.md
Created 3 new documents for **Mobile Web Applications** and updated meta descriptions for all docs under **Elements** as per the ticket https://testsigma.atlassian.net/browse/DOC-99. Please review.
Meta Title: ✔️
GIFs < 15 mb: ✔️
> Created 3 new docs for MWA

- src/pages/docs/desired-capabilities/incognito-mode.md
- src/pages/docs/test-management/test-plans/headless-testing.md
Updated Headless Browser Testing for the ticket https://testsigma.atlassian.net/browse/DOC-176.
Updated the Meta Description for the Run Browser in Incognito/Private Mode Document and added a new section for Desired Capabilities for Incognito or Private Browser.
SEO checklist
Meta Title Should have 60 Characters - ✅ 
@bharathk08
> Updated Headless Browser Testing Document 

- src/pages/docs/desired-capabilities/add-chrome-extension.md
- src/pages/docs/desired-capabilities/app-resigning.md
- src/pages/docs/desired-capabilities/avoid-unsafe-download-prompt.md
- src/pages/docs/desired-capabilities/custom-user-profile-chrome.md
- src/pages/docs/desired-capabilities/emulate-mobile-devices-with-chrome.md
- src/pages/docs/desired-capabilities/enable-browser-console-logs.md
- src/pages/docs/desired-capabilities/geo-location-for-localization.md
- src/pages/docs/desired-capabilities/most-common.md
- src/pages/docs/desired-capabilities/network-throttling.md
- src/pages/docs/desired-capabilities/overview.md
- src/pages/docs/desired-capabilities/screen-shot-capture.md
- src/pages/docs/desired-capabilities/set-geo-location.md
- src/pages/docs/desired-capabilities/webviews.md
- src/pages/docs/test-cases/manage/add-test-cases-for-mobile-web-app.md
Updated **Mobile Web Applications** doc as per the feedback & all Metas under **Desired Capabilities** section for the ticket https://testsigma.atlassian.net/browse/DOC-99.
> Updated MWA doc & meta descriptions

- src/components/navcards.jsx
- src/components/seo.jsx
- fixed 404 links on docs pages
- fixed inconsistent attribute values for robots meta tags
> WEB-513 - fixed 404 links on docs pages

- src/pages/docs/getting-started/testsigma-sample-apps.md
Updated App & URL links for Testsigma Sample Applications as per the ticket https://testsigma.atlassian.net/browse/DOC-204. Please review.
Meta Title: ✔️
> Updated Testsigma Sample Apps doc

- src/components/Footer.jsx
Update copyright info year from 2022 to 2023
> Update copyright info year from 2022 to 2023

- src/pages/docs/on-premise setup/smtp-configuration.md
Updated SMTP document as per the feedback. Please review.
Ticket - https://testsigma.atlassian.net/browse/DOC-206
> Updated SMTP document

- src/pages/docs/on-premise setup/post-installation-checklist.md
Updated on-prem installation checklist doc for post upgrade action items as per the doc https://testsigma.atlassian.net/browse/DOC-203.
Title: ✔️
> Updated on-prem installation checklist doc.

- src/pages/docs/on-premise setup/post-installation-checklist.md
- src/pages/docs/on-premise setup/smtp-configuration.md
Created a new doc SMTP changes & updated post installation checklist on-prem doc as per https://testsigma.atlassian.net/browse/DOC-203 & https://testsigma.atlassian.net/browse/DOC-206. Please review. 
Title: ✔️
> Created SMTP doc & updated on-prem doc

- src/pages/docs/collaboration/manage-execution-stops.md
Created new Document Control Who Can Stop Execution via Usage Details & Run Result for the ticket https://testsigma.atlassian.net/browse/DOC-205.
SEO checklist
Meta Title Should have 60 Characters - ✅
@bharathk08
> Created Control Who Can Stop Execution Document

- src/pages/docs/on-premise setup/custom-domain.md
Created a new doc for configuring custom domains for On-prem as per the doc https://testsigma.atlassian.net/browse/DOC-209. Please review. 
Title: ✔️
> Created a new doc for configuring custom domains

- src/pages/docs/troubleshooting/on-prem/general-issues.md
- src/pages/docs/troubleshooting/on-prem/restart-docker.md
Created a new doc for troubleshooting on-prem general issues as per the doc https://testsigma.atlassian.net/browse/DOC-210. Please review. 
Title: ✔️
> Added a new doc for troubleshooting on-prem issues

- src/pages/docs/troubleshooting/desktop-windows/recorder-failed.md
Created a new troubleshooting doc for Desktop Windows element recorder issue as per the doc https://testsigma.atlassian.net/browse/DOC-211. Please review.
> Created a troubleshooting doc for DW recorder

- src/pages/docs/test-data/bulk-deletion-of-test-data-profile.md
Updated bulk deletion of test Data Profiles as per the doc https://testsigma.atlassian.net/browse/DOC-212.
> Updated bulk deletion of TDP doc

- src/pages/docs/test-cases/create-steps-restapi/add-body-data.md
Created a new section GraphQL for the ticket https://testsigma.atlassian.net/browse/DOC-216.
SEO checklist
Meta Title Should have 60 Characters - ✅
@bharathk08
> Created GraphQL Document 

- src/pages/docs/collaboration/manage-execution-stops.md
- src/pages/docs/on-premise setup/custom-domain.md
- src/pages/docs/test-cases/create-steps-restapi/add-body-data.md
- src/pages/docs/test-data/bulk-deletion-of-test-data-profile.md
- src/pages/docs/troubleshooting/desktop-windows/recorder-failed.md
- src/pages/docs/troubleshooting/on-prem/general-issues.md
- src/pages/docs/troubleshooting/on-prem/restart-docker.md
New docs are added for troubleshooting On-prem & Desktop windows as per the tickets https://testsigma.atlassian.net/browse/DOC-211 & https://testsigma.atlassian.net/browse/DOC-210. These docs are approved for main site.
> New troubleshooting docs for ON-prem & DWs

- src/pages/docs/test-cases/image-injection.md
Updated an Image Injection document and created a new section for Camera Image Injection for the ticket https://testsigma.atlassian.net/browse/DOC-217.
SEO checklist
Meta Title Should have 60 Characters - ✅
@bharathk08
> Updated Image Injection document

- src/pages/docs/test-cases/create-steps-nl/reorder.md
> Dummmy Commit

- src/components/Footer.scss
fix: Footer CTA banner UI issue
> fix: Footer CTA banner UI issue

- src/pages/docs/desired-capabilities/enable-browser-console-logs.md
- src/pages/docs/elements/overview.md
- src/pages/docs/runs/adhoc-runs.md
- src/pages/docs/test-cases/create-steps-nl/reorder.md
- src/pages/docs/test-cases/step-types/block.md
- src/pages/docs/test-cases/step-types/rest-api.md
- src/pages/docs/test-management/test-plans/headless-testing.md
- src/pages/docs/uploads/upload-apps.md
- src/pages/docs/visual-testing/configure-test-steps.md
Following docs as per React UI - Set 2: https://testsigma.atlassian.net/browse/DOC-226
Test Step Type: Blocks - https://testsigma.com/docs/test-cases/step-types/block/
Visual Testing - https://testsigma.com/docs/visual-testing/configure-test-steps/
Ad-hoc Run - https://testsigma.com/docs/runs/adhoc-runs/
Enable Browser Console Debug Logs - https://testsigma.com/docs/desired-capabilities/enable-browser-console-logs/
Element List Actions - https://testsigma.com/docs/elements/overview/
Test Step Reordering - https://testsigma.com/docs/test-cases/create-steps-nl/reorder/
Upload Android and iOS Apps - https://testsigma.com/docs/uploads/upload-apps/
Updated Test Step Type: Rest API Test Step Type - Rest API - https://testsigma.com/docs/test-cases/step-types/rest-api/
gif for the ticket …
> Updated Documents as per React UI - Set 2

- .github/workflows/cd.yml
fix: Removing env file if already exists in prod build file
> fix: Removing env file if already exists in prod build file

- src/components/seo.jsx
fix: Updated the staging hubspot account ID to prod
> fix: Updated the staging hubspot account ID to prod

- src/pages/docs/desired-capabilities/geo-location-for-localization.md
- src/pages/docs/integrations/bug-reporting/jira.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/reports/runs/test-case-reports.md
- src/pages/docs/test-cases/step-types/natural-language.md
- src/pages/docs/test-data/types/raw.md
Update the following docs as per new UI:
https://testsigma.com/docs/integrations/bug-reporting/jira/
https://testsigma.com/docs/projects/settings/test-case-types/
https://testsigma.com/docs/desired-capabilities/geo-location-for-localization/
https://testsigma.com/docs/reports/runs/test-case-reports/
https://testsigma.com/docs/test-data/types/raw/
https://testsigma.com/docs/test-cases/step-types/natural-language/
> Updated the docs as per new UI

- src/pages/docs/test-cases/create-steps-nl/step-actions.md
- src/pages/docs/test-cases/create-steps-nl/step-settings.md
- src/pages/docs/test-data/create-environment-data.md
- src/pages/docs/test-data/types/data-generator.md
Following docs as per React UI - Set 4: https://testsigma.atlassian.net/browse/DOC-234
Test Step Options - https://testsigma.com/docs/test-cases/create-steps-nl/step-actions/
Test Step Settings - https://testsigma.com/docs/test-cases/create-steps-nl/step-settings/
Test Data Type: Data Generator - https://testsigma.com/docs/test-data/types/data-generator/
Create Environment Test Data - https://testsigma.com/docs/test-data/create-environment-data/
> Updated Documents as per React UI - Set 4

- src/pages/docs/configuration/security/google-sso.md
- src/pages/docs/configuration/security/overview.md
- src/pages/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures.md
Update the following docs as per new UI:
https://testsigma.com/docs/configuration/security/google-sso/
https://testsigma.com/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures/
https://testsigma.com/docs/configuration/security/overview/
> Updated the following docs as per new UI

- src/pages/docs/projects/versions.md
- src/pages/docs/test-cases/create-steps-recorder/android-apps/controls-and-actions.md
Updated the following docs as per new UI:
https://testsigma.com/docs/projects/versions/
https://testsigma.com/docs/test-cases/create-steps-recorder/android-apps/controls-and-actions/
> Updated following docs as per new UI

- src/pages/docs/test-cases/step-types/step-group.md
- src/pages/docs/test-data/types/phone-number.md
Updated the following docs as per feedback by Divesh. 
https://testsigma.com/docs/test-data/types/phone-number/
https://testsigma.com/docs/test-cases/step-types/step-group/
> Updated the following docs as per the feedback

- src/pages/docs/elements/overview.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
- src/pages/docs/test-cases/manage/list-actions.md
- src/pages/docs/test-cases/step-types/block.md
- src/pages/docs/test-cases/step-types/rest-api.md
- src/pages/docs/test-data/types/runtime.md
- src/pages/docs/test-management/test-plans/schedule-plans.md
- src/pages/docs/visual-testing/configure-test-steps.md
Following docs as per React UI - Set 5: https://testsigma.atlassian.net/browse/DOC-255
Visual Testing: https://testsigma.com/docs/visual-testing/configure-test-steps/
Test Cases List Actions: https://testsigma.com/docs/test-cases/manage/list-actions/
Schedule Test Plans: https://testsigma.com/docs/test-management/test-plans/schedule-plans/
Element List Actions: https://testsigma.com/docs/elements/overview/
Test Data Type: Runtime: https://testsigma.com/docs/test-data/types/runtime/
Test Step Type: Rest API: https://testsigma.com/docs/test-cases/step-types/rest-api/
Test Cases: https://testsigma.com/docs/test-cases/manage/add-edit-delete/
Test Step Type: Block: https://testsigma.com/docs/test-cases/step-types/block/#deleting-a-block
> Updated Documents as per React UI - Set 5

- src/templates/page.scss
- UI issues of cookie banner on docs.
> fix: UI issues of cookie banner on docs.

- src/pages/docs/api/examples/update-test-case-results-using-API.md
- src/pages/docs/api/overview.md
Updated **Testsigma API Overview** doc with GET IDs of Projects, Applications and Uploads content.
> Updated Testsigma API Overview doc

- src/pages/docs/test-data/create-data-profiles.md
Updated Test Data Profiles doc with a subsection - **Data-driven Testing with Dynamic Data Sets**.
> Updated Test Data Profiles document.

- src/templates/page.scss
> fix: inner linking scroll position

- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-management/test-plans/overview.md
- src/pages/docs/test-management/test-suites/overview.md
Following docs as per React UI - Set 6: https://testsigma.atlassian.net/browse/DOC-256
Test Plans: https://testsigma.com/docs/test-management/test-plans/overview/
Test Suites: https://testsigma.com/docs/test-management/test-suites/overview/
Test Data Type: Mail Box: https://testsigma.com/docs/test-data/types/mailbox/
> Updated Documents as per React UI - Set 6

- src/pages/docs/continuous-integration/aws-devops.md
- src/pages/docs/continuous-integration/github-cicd.md
- src/pages/docs/integrations/collaboration/microsoft-teams.md
- src/pages/docs/integrations/product-management/clickup.md
- src/pages/docs/integrations/product-management/linear.md
- src/pages/docs/test-management/test-plans/manage-test-machines.md
Updated metas for 5 docs and Test Machine doc as per new UI.
> Updated 5 Metas  & Test Machine document

- src/pages/docs/elements/android-apps/create-manually.md
- src/pages/docs/elements/ios-apps/create-manually.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/test-cases/create-steps-restapi/add-body-data.md
- src/pages/docs/test-cases/create-steps-restapi/adding-headers.md
- src/pages/docs/test-cases/create-steps-restapi/adding-parameters.md
- src/pages/docs/test-cases/create-steps-restapi/api-resquest.md
- src/pages/docs/test-cases/create-steps-restapi/attachments-rest-api.md
- src/pages/docs/test-cases/create-steps-restapi/authorization-request.md
- src/pages/docs/test-cases/create-steps-restapi/restful-api-overview.md
- src/pages/docs/test-cases/create-steps-restapi/store-variables.md
- src/pages/docs/test-cases/create-steps-restapi/stored-objects.md
- src/pages/docs/test-cases/create-steps-restapi/verifications-request.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-cases/create-test-steps/overview.md
Revamped Test Cases section in documentation since there was more duplicate content.
> Revamped Test Cases section in documentation

- src/pages/docs/elements/android-apps/capture-single-element.md
- src/pages/docs/elements/ios-apps/capture-single-element.md
- src/pages/docs/elements/overview.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/reports/runs/drill-down-reports.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/test-cases/create-steps-recorder/android-apps/reuse-elements.md
- src/pages/docs/test-cases/create-steps-recorder/ios-apps/update-elements.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/add-steps-manually.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/reorder.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/reuse-elements.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/update-elements.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/controls-and-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/multiple-webviews.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-settings.md
- src/pages/docs/test-data/types/mailbox.md
Migrated all the content that was duplicate under Test Cases section (Test Step Creation docs)
> Updated Test Cases Content Section

- src/left-nav-title.json
- src/pages/docs/reports/runs/drill-down-reports.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-settings.md
Content updated for migrated docs.
> Content updated for migrated docs.

- src/templates/page.scss
Added styling for black friday deal campaign hello bar
> Added styling for black friday deal campaign hello bar

- src/templates/page.scss
fix: Black friday deal hello bar UI issue fixed
> fix: Black friday deal hello bar UI issue fixed

- src/templates/page.scss
fix: Black Friday deal hello bar UI issue fixed (#333)
> Dev to main [27 Nov]

- src/left-nav-title.json
- src/pages/docs/elements/android-apps/capture-single-element.md
- src/pages/docs/elements/android-apps/create-manually.md
- src/pages/docs/elements/android-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/android-apps/overview.md
- src/pages/docs/elements/android-apps/record-multiple-elements.md
- src/pages/docs/elements/android-apps/supported-locator-types.md
- src/pages/docs/elements/desktop-windows/record-elements.md
- src/pages/docs/elements/dynamic-elements/with-environment-data.md
- src/pages/docs/elements/dynamic-elements/with-parameter-test-data.md
- src/pages/docs/elements/dynamic-elements/with-runtime-test-data.md
- src/pages/docs/elements/import-export.md
- src/pages/docs/elements/ios-apps/capture-single-element.md
- src/pages/docs/elements/ios-apps/overview.md
- src/pages/docs/elements/ios-apps/record-multiple-elements.md
- src/pages/docs/elements/mobile-web-application/create-manually.md
- src/pages/docs/elements/mobile-web-application/record-elements.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/elements/web-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/web-apps/iframe-elements.md
- src/pages/docs/elements/web-apps/overview.md
- src/pages/docs/elements/web-apps/record-multiple-elements.md
- src/pages/docs/elements/web-apps/shadow-dom.md
- src/pages/docs/elements/web-apps/supported-locator-types.md
- src/pages/docs/elements/web-apps/verify-elements.md
Revamped entire elements section as per new UI.
> Bulk updated Elements section as per new UI.

- src/left-nav-title.json
- src/pages/docs/collaboration/assign-projects.md
- src/pages/docs/collaboration/deleting-users-from-a-project.md
- src/pages/docs/collaboration/elements-review-management.md
- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/collaboration/manage-execution-stops.md
- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/getting-started/faqs.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/getting-started/introduction-community.md
- src/pages/docs/getting-started/setup/docker.md
- src/pages/docs/getting-started/setup/downloadable-package.md
- src/pages/docs/getting-started/setup/overview.md
- src/pages/docs/getting-started/setup/testsigma-cloud.md
- src/pages/docs/getting-started/telemetry.md
- src/pages/docs/getting-started/terminology.md
- src/pages/docs/getting-started/testsigma-community-cloud.md
- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/projects/applications.md
- src/pages/docs/projects/settings/requirement-types.md
- src/pages/docs/test-data/add-values-to-test-data-profile.md
- src/pages/docs/test-data/types/concat.md
- src/pages/docs/test-data/update-test-data-profile.md
Updated Getting started, Collaboration & Test Data Management sections as per new UI.
> Updated Getting started, Collab & Test Data Sections

- src/pages/docs/addons/ocr-extraction.md
- src/pages/docs/desired-capabilities/incognito-mode.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/integrations/test-labs/browserstack.md
- src/pages/docs/integrations/test-labs/integrate-test-labs.md
- src/pages/docs/integrations/test-labs/kobiton.md
- src/pages/docs/integrations/test-labs/lambdatest.md
- src/pages/docs/integrations/test-labs/sauce-labs.md
- src/pages/docs/reports/export-reports/export-report-pdf.md
- src/pages/docs/reports/export-reports/export-report-xls.md
- src/pages/docs/reports/export-reports/export-reports-junit.md
- src/pages/docs/test-cases/manage/import-from-yaml-or-git.md
- src/pages/docs/test-cases/manage/import-postman-to-testsigma.md
- src/pages/docs/test-management/test-plans/disable-test-cases-in-test-plans.md
- src/pages/docs/test-management/test-plans/partial-test-plan-run-via-api.md
- src/pages/docs/test-management/test-plans/post-plan-hook.md
Following docs as per React UI - Set 7: https://testsigma.atlassian.net/browse/DOC-259
Create OCR Text Extraction Addon - https://testsigma.com/docs/addons/ocr-extraction/
Run Browser in Incognito/Private mode - https://testsigma.com/docs/desired-capabilities/incognito-mode/
Entering Non-Text Keys in Test Cases - https://testsigma.com/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases/
Post Plan Hook - https://testsigma.com/docs/test-management/test-plans/post-plan-hook/
Execute Partial Test Plan Run via API - https://testsigma.com/docs/test-management/test-plans/partial-test-plan-run-via-api/
Integrations with Test Labs - https://testsigma.com/docs/integrations/test-labs/integrate-test-labs/
(https://testsigma.com/docs/integrations/test-labs/browserstack/, …
> Updated Documents as per React UI - Set 7

- src/pages/docs/troubleshooting/setup/prerequisites-for-cloud-executions.md
Deleted prerequisites for cloud executions doc from getting started and added the same with updated content under **Troubleshooting > Setup > Secured Business Application Support**.
> Updated prerequisites for cloud doc.

- src/pages/docs/troubleshooting/on-prem/general-issues.md
Replaced 404 URL with proper URL
> fix: Replaced 404 URL with proper URL

- src/components/navcards.jsx
- src/pages/docs/troubleshooting/on-prem/general-issues.md
- Replaced 404 URL with proper URL
> Dev: 404 links fixation

- src/pages/docs/elements/auto-healing.md
- src/pages/docs/test-data/types/mailbox.md
Created a new doc for Auto Healing & Updated MailBox doc with a sample Test Case as per the tickets https://testsigma.atlassian.net/browse/IDEA-860 & https://testsigma.atlassian.net/browse/IDEA-883. These docs are approved in staging.
> Auto Healing (New) & Mailbox Doc (Updated)

- src/pages/docs/troubleshooting/setup/secured-business-application-support.md
- src/pages/docs/troubleshooting/setup/troubleshooting-restricted-access.md
Added a new doc for Troubleshooting Restricted Access to Testsigma as per the ticket https://testsigma.atlassian.net/browse/IDEA-937.
> Troubleshooting doc for restricted access to testsigma

- src/pages/docs/desired-capabilities/network-logs.md
Updated Network Logs for the ticket: https://testsigma.atlassian.net/browse/IDEA-925
> Updated Network Logs Documents as per React UI

- src/pages/docs/test-cases/image-injection.md
Updated Image Injection for the ticket: https://testsigma.atlassian.net/browse/IDEA-926
> Updated Image Injection Documents as per React UI

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/basic-authentication.md
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/trigger-tests-locally.md
- src/pages/docs/agent/troubleshooting/logs.md
- src/pages/docs/desired-capabilities/overview.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/runs/test-locally-hosted-applications.md
Created new docs for Triggering Tests Locally, Basic Authentication for Web and updated names in left nav bar & few docs as per new UI.
> New docs for Triggering Tests Locally and authentication for Web

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/basic-authentication.md
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/trigger-tests-locally.md
- src/pages/docs/agent/troubleshooting/logs.md
- src/pages/docs/desired-capabilities/network-logs.md
- src/pages/docs/desired-capabilities/overview.md
- src/pages/docs/elements/auto-healing.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-cases/image-injection.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/troubleshooting/setup/secured-business-application-support.md
- src/pages/docs/troubleshooting/setup/troubleshooting-restricted-access.md
New docs added for Auto Healing, Triggering Tests Locally, Basic Authentication for Web Pages and Whitelisting Restricted Access to Testsigma. 
Updated MailBox doc
> New doc for Auto Healing & Test Case added to MailBox doc

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/basic-authentication.md
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/trigger-tests-locally.md
- src/pages/docs/agent/troubleshooting/logs.md
- src/pages/docs/desired-capabilities/network-logs.md
- src/pages/docs/desired-capabilities/overview.md
- src/pages/docs/elements/auto-healing.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-cases/image-injection.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/troubleshooting/setup/secured-business-application-support.md
- src/pages/docs/troubleshooting/setup/troubleshooting-restricted-access.md
Updated phone number doc with setting up SMS Forwarding App & use case related to it. Verified in Staging.
> Updated phone number document with use case

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/basic-authentication.md
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/agent/trigger-tests-locally.md
- src/pages/docs/agent/troubleshooting/logs.md
- src/pages/docs/configuration/generate-wda-file.md
- src/pages/docs/desired-capabilities/network-logs.md
- src/pages/docs/desired-capabilities/overview.md
- src/pages/docs/elements/auto-healing.md
- src/pages/docs/faqs/web-apps/how-to-enter-non-text-keys-in-test-cases.md
- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/multiple-webviews.md
- src/pages/docs/test-cases/image-injection.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
- src/pages/docs/troubleshooting/mobile-apps/click-tap-failure.md
- src/pages/docs/troubleshooting/setup/secured-business-application-support.md
- src/pages/docs/troubleshooting/setup/troubleshooting-restricted-access.md
- src/pages/docs/troubleshooting/web-apps/issues-with-ui-Identifiers.md
Created new troubleshooting docs for Web & Mobile and creation of WDA file. Please review.
> New troubleshooting & WDA file creation docs. 

- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/configuration/ios-settings.md
- src/pages/docs/configuration/reset-password.md
- src/pages/docs/configuration/storage-types.md
- src/pages/docs/desired-capabilities/most-common.md
- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
Updated Testsigma's Best Practice document for the ticket: https://testsigma.atlassian.net/browse/IDEA-990
Updated Screenshots for Configuring Local iOS Device with Provisioning Profile Document for the ticket: https://testsigma.atlassian.net/browse/IDEA-901
Added Android & iOS sections in the Common Desired Capabilities document for the ticket: https://testsigma.atlassian.net/browse/IDEA-895
> Updated Best Practices and Provisional Profile docs

- src/left-nav-title.json
- src/pages/docs/configuration/generate-wda-file.md
- src/pages/docs/troubleshooting/web-apps/chrome-settings.md
Created a new doc for Troubleshooting missing elements while using recorder as per the ticket https://testsigma.atlassian.net/browse/IDEA-881. Please review.
> Troubleshooting doc for missing elements

- src/left-nav-title.json
- src/pages/docs/test-step-recorder/install-chrome-extension.md
Updated Installing Chrome Extension Doc with steps to enable in Recorder Extension to record steps in Incognito.
> Updated Chrome Installer Document

- src/pages/docs/test-step-recorder/install-chrome-extension.md
- src/pages/docs/test-step-recorder/install-edge-extension.md
Updated interlinks in recorder extension docs
> Updated Interlinks in Extension Docs

- src/left-nav-title.json
- src/pages/docs/test-step-recorder/install-chrome-extension.md
- src/pages/docs/test-step-recorder/install-edge-extension.md
- src/pages/docs/test-step-recorder/install-firefox-extension.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
Added a new document for Testsigma Recorder Extension for Edge.
> Added new doc for Recorder Extension: Edge 

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/automating-captcha.md
Added a new document for FAQs on CAPTCHA Automation as per the ticket https://testsigma.atlassian.net/browse/IDEA-1085.
> Added FAQ document for CAPTCHA Automation

- src/left-nav-title.json
- src/pages/docs/desired-capabilities/app-resigning.md
- src/pages/docs/desired-capabilities/avoid-unsafe-download-prompt.md
- src/pages/docs/desired-capabilities/custom-user-profile-chrome.md
- src/pages/docs/desired-capabilities/emulate-mobile-devices-with-chrome.md
- src/pages/docs/desired-capabilities/geo-location-for-localization.md
- src/pages/docs/desired-capabilities/incognito-mode.md
- src/pages/docs/desired-capabilities/screen-shot-capture.md
- src/pages/docs/desired-capabilities/set-geo-location.md
- src/pages/docs/desired-capabilities/set-playstore-credentials.md
- src/pages/docs/desired-capabilities/webviews.md
Added a new document for setting Google Play Store creds using desired capabilities & updated titles in Left Nav Bar for DC section to maintain uniformity.
> Added a doc for Google Play Store (DC)

- src/pages/docs/agent/setup-on-windows-mac-linux.md
Updated Agent Setup Document Using Docker to fetch the docker logs in local machines.
> Updated Agent Setup Document

- src/left-nav-title.json
- src/pages/docs/FAQs/web-apps/automating-captcha.md
- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/desired-capabilities/app-resigning.md
- src/pages/docs/desired-capabilities/avoid-unsafe-download-prompt.md
- src/pages/docs/desired-capabilities/custom-user-profile-chrome.md
- src/pages/docs/desired-capabilities/emulate-mobile-devices-with-chrome.md
- src/pages/docs/desired-capabilities/geo-location-for-localization.md
- src/pages/docs/desired-capabilities/incognito-mode.md
- src/pages/docs/desired-capabilities/screen-shot-capture.md
- src/pages/docs/desired-capabilities/set-geo-location.md
- src/pages/docs/desired-capabilities/set-playstore-credentials.md
- src/pages/docs/desired-capabilities/webviews.md
Added CAPTCHA & Google Play Store Capabilities docs.
> Added CAPTCHA & Play Store Capabilities

- src/left-nav-title.json
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/element-repos.md
- src/pages/docs/salesforce-testing/introduction.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
Added Salesforce links to integrate in the production. The links will be updated with the content.
> Added doc links for SF Testing

- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/introduction.md
Added Salesforce Introduction, Connected App & Project docs as per the tickets https://testsigma.atlassian.net/browse/IDEA-1016 and https://testsigma.atlassian.net/browse/IDEA-1015.
> Added SF Intro, Connected App & Project Docs

- src/left-nav-title.json
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/element-repos.md
- src/pages/docs/salesforce-testing/introduction.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
Add all Salesforce Documents as part of Salesforce GA release. 
https://website.testsigma.com/docs/salesforce-testing/introduction/
https://website.testsigma.com/docs/salesforce-testing/connected-app/
https://website.testsigma.com/docs/salesforce-testing/create-sf-project/
https://website.testsigma.com/docs/salesforce-testing/metadata-connections/
https://website.testsigma.com/docs/salesforce-testing/user-connections/
https://website.testsigma.com/docs/salesforce-testing/sf-test-cases/
https://website.testsigma.com/docs/salesforce-testing/element-repos/
https://website.testsigma.com/docs/salesforce-testing/special-nlps/
> Added all Salesforce Documents

- src/left-nav-title.json
- src/pages/docs/elements/locator-precedence.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/elements/web-apps/creating-locators-manually-strategies.md
- src/pages/docs/elements/web-apps/record-multiple-elements.md
- src/pages/docs/elements/web-apps/verify-elements.md
Added a new doc for Configuring Locator Precedence in Recorder.
> Added a new doc for Locator Precedence

- src/left-nav-title.json
- src/pages/docs/salesforce-testing/error-handling.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
Added Error handling & activity logs for Salesforce.
> Added error handling & activity logs for SF

- src/pages/docs/agent/troubleshooting/logs.md
Updated Agent Logs Document on how to send logs automatically & manually.
> Updated Agent Logs Document

- src/pages/docs/test-cases/create-steps-restapi/store-variables.md
- src/pages/docs/test-cases/create-steps-restapi/verifications-request.md
Updated existing Verifications & Store Variables for HTML response.
> Added Verifications & Store Variables for APIs

- src/pages/docs/agent/soft-delete-agents.md
- src/pages/docs/agent/trigger-tests-locally.md
Added a new document for Agent soft delete.
> Added a new doc for Agent soft delete

- src/pages/docs/agent/soft-delete-agents.md
> Corrected grammar mistake

- src/pages/docs/elements/verify-elements.md
- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
Added a new doc for verifying elements from test recorder.
> Added a doc for verifying elements from recorder.

- src/pages/docs/agent/troubleshooting/logs.md
Added Agent Log Level Configuration section and updated Agent Logs document for the ticket. Please review
> Added Agent Log Level Configuration section

- src/pages/docs/runs/executing-tests-in-private-grid.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/metadata-connections.md
Added a new doc for test executions on Testsigma Private Grid as per the ticket https://testsigma.atlassian.net/browse/IDEA-1627.
> Added a new doc for Testsigma Private Grid

- src/pages/docs/agent/troubleshooting/logs.md
- src/pages/docs/runs/executing-tests-in-private-grid.md
- src/pages/docs/runs/test-plans-on-local-devices.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/metadata-connections.md
Added a new doc for executing tests on Testsigma Private Grid. This is verified on staging.
> Added a new doc for test executions on Private Grid

- src/left-nav-title.json
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/troubleshooting/salesforce-testing/most-common-issues.md
Added a new Troubleshooting doc & updated special NLPs doc for salesforce.
> Added Troubleshooting doc for Salesforce

- src/left-nav-title.json
- src/pages/docs/configuration/security/okta-sso.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/troubleshooting/salesforce-testing/most-common-issues.md
Added a new troubleshooting doc for Salesforce & updated SSO document.
> New troubleshooting doc for Salesforce & SSO doc update

- src/pages/docs/integrations/collaboration/google-chat.md
- src/pages/docs/integrations/collaboration/microsoft-teams.md
- src/pages/docs/integrations/collaboration/slack.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/controls-and-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/step-settings.md
- src/pages/docs/test-cases/step-types/block.md
- src/pages/docs/test-cases/step-types/for-loop.md
- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-cases/step-types/while-loop.md
Mobile Recorder Document Bulk Update.
> Mobile Recorder Documents Bulk Update

- src/pages/docs/test-data/data-generators/name-function-type.md
Added new document for Name Function Type as per the ticket https://testsigma.atlassian.net/browse/IDEA-911. Please review.
> Added Name Function Type Document

- src/pages/docs/test-data/types/environment.md
Updated the Environment document with steps to add Variables globally to add variables to all Environments at once.
> Updated the Environment document

- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/test-data/types/environment.md
> Update Test Locally Hosted Apps

- src/pages/docs/test-data/data-generators/address-function-type.md
- src/pages/docs/test-data/data-generators/company-function-type.md
- src/pages/docs/test-data/data-generators/file-function-type.md
- src/pages/docs/test-data/data-generators/idnumber-function-type.md
Added new document for Address Function Type
Added new document for Company Function Type
Added new document for File Function Type
Added new document for IdNumber Function Type
Updated Name Function Type Document
> Added Address, Company, File & IdNumber Document

- src/pages/docs/test-data/data-generators/emailfunctions-function-type.md
- src/pages/docs/test-data/data-generators/internet-function-type.md
- src/pages/docs/test-data/data-generators/mailboxfunctions-function-type.md
- src/pages/docs/test-data/data-generators/number-function-type.md
Added new document for EmailFunctions Function Type
Added new document for Internet Function Type
Added new document for Number Function Type
Added new document for MailBoxFunctions Function Type
> Added EmailFunctions, Number, Internet & MailBoxFunctions Data Generator Document

- src/pages/docs/test-data/data-generators/address-function-type.md
- src/pages/docs/test-data/data-generators/company-function-type.md
- src/pages/docs/test-data/data-generators/datefunctions-function-type.md
- src/pages/docs/test-data/data-generators/emailfunctions-function-type.md
- src/pages/docs/test-data/data-generators/friends-function-type.md
- src/pages/docs/test-data/data-generators/mailboxaliasfunctions-function-type.md
- src/pages/docs/test-data/data-generators/mailboxfunctions-function-type.md
- src/pages/docs/test-data/data-generators/stringfunctions-function-type.md
- src/pages/docs/test-data/data-generators/testdatafromprofile-function-type.md
Added new document for MailBoxAlias Function Type
Added new document for Date Function Type
Added new document for String Function Type
Added new document for Friends Function Type
Added new document for TestDataFromProfile Function Type
Updated Email, Address, Company and MailBox Functions document based on feedback
> Added MailBoxAlias, String, Friends and Date Functions Document

- src/left-nav-title.json
- src/pages/docs/test-cases/create-steps-restapi/add-body-data.md
- src/pages/docs/test-cases/create-steps-restapi/mock-apis.md
- src/pages/docs/test-cases/create-steps-restapi/restful-api-overview.md
- src/pages/docs/test-cases/create-steps-restapi/stored-objects.md
- src/pages/docs/test-management/test-plans/supported-test-lab-types.md
Added a new doc for Mock API support in Testsigma
> Added doc for Mock API Support

- src/pages/docs/test-data/data-generators/address-function-type.md
- src/pages/docs/test-data/data-generators/change-data-type-function-type.md
- src/pages/docs/test-data/data-generators/company-function-type.md
- src/pages/docs/test-data/data-generators/datefunctions-function-type.md
- src/pages/docs/test-data/data-generators/domainfunctions-function-type.md
- src/pages/docs/test-data/data-generators/emailfunctions-function-type.md
- src/pages/docs/test-data/data-generators/file-function-type.md
- src/pages/docs/test-data/data-generators/idnumber-function-type.md
- src/pages/docs/test-data/data-generators/internet-function-type.md
- src/pages/docs/test-data/data-generators/mailboxaliasfunctions-function-type.md
- src/pages/docs/test-data/data-generators/mailboxfunctions-function-type.md
- src/pages/docs/test-data/data-generators/name-function-type.md
- src/pages/docs/test-data/data-generators/namefunctions-function-type.md
- src/pages/docs/test-data/data-generators/number-function-type.md
- src/pages/docs/test-data/data-generators/numberfunctions-function-type.md
- src/pages/docs/test-data/data-generators/phone-function-type.md
- src/pages/docs/test-data/data-generators/phonenumberfunctions-function-type.md
- src/pages/docs/test-data/data-generators/random-string-function-type.md
- src/pages/docs/test-data/data-generators/random-text-function-type.md
- src/pages/docs/test-data/data-generators/stringfunctions-function-type.md
- src/pages/docs/test-data/data-generators/testdatafromprofile-function-type.md
- src/pages/docs/test-data/types/environment.md
Added new document for NameFunctions Function Type
Added new document for NumberFunctions Function Type
Added new document for Random String Function Type
Added new document for RandomText Function Type
Added new document for ChangeDataType Function Type
Added new document for Phone Number Function Type
Added new document for PhoneNumberFunctions Function Type
Changed all Data Generators order pages based on Data Generators
Added new section Use Environment Variables to Select Test Data Values for the ticket https://testsigma.atlassian.net/browse/IDEA-1684
> Updated all Data Generator Document

- src/pages/docs/test-data/data-generators/address-function-type.md
- src/pages/docs/test-data/data-generators/change-data-type-function-type.md
- src/pages/docs/test-data/data-generators/datefunctions-function-type.md
- src/pages/docs/test-data/data-generators/emailfunctions-function-type.md
- src/pages/docs/test-data/data-generators/mailboxaliasfunctions-function-type.md
- src/pages/docs/test-data/data-generators/mailboxfunctions-function-type.md
- src/pages/docs/test-data/data-generators/number-function-type.md
- src/pages/docs/test-data/data-generators/phonenumberfunctions-function-type.md
- src/pages/docs/test-data/data-generators/random-string-function-type.md
- src/pages/docs/test-data/data-generators/stringfunctions-function-type.md
- src/pages/docs/test-data/data-generators/testdatafromprofile-function-type.md
Updated Data Generators Documents based on Feedback
> Updated Data Generators Documents - 1

- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/test-cases/manage/update-test-case-results-in-a-test-plan.md
Updated test case result updation in test plan document. Please review
> Updated test case result updation document

- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/test-data/data-generators/datefunctions-function-type.md
- src/pages/docs/test-data/data-generators/phonenumberfunctions-function-type.md
Updated Debugging Results on Local Devices for Web Applications Document for the ticket https://testsigma.atlassian.net/browse/IDEA-1736
> Updated Debugging Results on Local Devices for Web Applications Document

- src/templates/page.scss
- Cookie banner UI issue -> Fixed
> [Fixed] -> Cookie banner UI issue

- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ce.md
- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ue.md
- src/pages/docs/contributing/open-source-dev-environment-setup/windows-and-intelliJ-ue.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/troubleshooting/on-prem/general-issues.md
Updated Copilot documentation with images and removed 404 links in doc pages.
> Updated Copilot docs & Removed 404 links

- scripts/indexr.js
- src/components/SearchHits.jsx
- src/components/SearchHits.scss
- src/components/SearchInputBox.jsx
- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ce.md
- src/pages/docs/contributing/open-source-dev-environment-setup/macos-and-intellij-ue.md
- src/pages/docs/contributing/open-source-dev-environment-setup/windows-and-intelliJ-ue.md
- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/debugging/launch-the-debugger-in-the-same-window.md
- src/pages/docs/debugging/results-on-local-devices.md
- src/pages/docs/getting-started/introduction-cloud.md
- src/pages/docs/reports/runs/custom-pdf-report.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/troubleshooting/on-prem/general-issues.md
- src/templates/page.scss
- Added custom PDF document, 
- Updated Copilot docs, 
- Removed 404 links and 
- Fixed the Typesense search bar input cache
> [Dev] >>> Added custom PDF document, Updated Copilot docs, Removed 404 links and Fixed the Typesense input cache validation

- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/troubleshooting/salesforce-testing/most-common-issues.md
- src/pages/docs/windows-automation/introduction.md
Updated Connected App doc for Salesforce as per the ticket https://testsigma.atlassian.net/browse/IDEA-1716.
> Updated Connected App doc for Salesforce

- scripts/indexr.js
- src/components/SearchHits.scss
- src/components/SearchInputBox.jsx
- src/components/layout.jsx
- Search results repeating issue on docs search
> [Fixed] -> Search results repeating issue on docs search

- scripts/indexr.js
- src/components/SearchHits.scss
- src/components/SearchInputBox.jsx
- src/components/layout.jsx
- src/components/navcards.jsx
- src/pages/docs/on-premise-setup/pre-installation/testsigma-on-prem-architecture.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/troubleshooting/salesforce-testing/most-common-issues.md
- src/pages/docs/windows-automation/introduction.md
- Added deployment diagram to On-prem doc and updated On-prem setup widget inner link on docs
> [Dev] >>> Added deployment diagram to On-prem doc and updated On-prem setup widget innerlink on docs

- src/pages/docs/debugging/results-on-local-devices.md
- src/pages/docs/reports/runs/custom-pdf-report.md
Updated Custom PDF Report Generation and Debugging Mobile Applications Docs based on the Feedback:
> Updated Custom PDF Report Generation and Debugging Mobile Applications Docs

- src/pages/docs/addons/create.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
Updated the content and visuals for the Creating an Addon document for the ticket: https://testsigma.atlassian.net/browse/IDEA-1798.
> Updated Creating an Addon Doc

- src/pages/docs/api/get-project-wide-information.md
- src/pages/docs/api/test-results-at-all-levels.md
Updated API doc with proper table & intro for Project Wide Info.
> Updated API doc for Project Wide Info

- .github/workflows/staging-cd.yml
> Updated AWS secret keys

- .github/workflows/staging-cd.yml
- Checking graphql url using curl -v
> Checking graphql url using curl -v

- .github/workflows/cd.yml
- Downgraded node version from 18 to 16
> [Revert] -> Downgraded node version from 18 to 16

- src/pages/docs/FAQs/web-apps/failure-to-link-text-capture.md
- src/pages/docs/FAQs/web-apps/viewing-full-testplan-execution-video.md
- src/pages/docs/FAQs/web-apps/visual-differences-ignored-areas.md
- src/pages/docs/debugging/results-on-local-devices.md
Created Test Case Failures Due to Link Text Capture Issues Doc for the ticket: https://testsigma.atlassian.net/browse/IDEA-1823
Created Viewing the Full Video of the Test Plan Execution Doc for the ticket: https://testsigma.atlassian.net/browse/IDEA-1825
Created Visual Differences Not Highlighted in Ignored Areas of Test Case Doc for the ticket: https://testsigma.atlassian.net/browse/IDEA-1828
Updated Debugging Mobile Applications on Local Devices Doc for the ticket: https://testsigma.atlassian.net/browse/IDEA-1737
> Added 3 New FAQs & Updated Mobile Debugger Documentations

- src/pages/docs/salesforce-testing/error-handling.md
Updated Error Handling document with Handling Deprecated Elements section.
> Updated Error Handling document

- src/pages/docs/FAQs/web-apps/viewing-full-testplan-execution-video.md
- src/pages/docs/visual-testing/configure-test-steps.md
Updated images and added a note for Visual Testing with ignore sections
> Updated Watch Video doc

- src/left-nav-title.json
- src/pages/docs/continuous-integration/copado-integration.md
- src/pages/docs/continuous-integration/gitlab-cicd.md
- src/pages/docs/continuous-integration/shell-script.md
Added a new doc for Copado Integration with Testsigma.
> Added a new document for Copado Integration

- src/pages/docs/contributing/open-source-dev-environment-setup/windows-and-intelliJ-ue.md
> Fix: Pages having http link

- src/pages/docs/agent/setup-on-windows-mac-linux.md
- src/pages/docs/contributing/open-source-dev-environment-setup/windows-and-intelliJ-ue.md
- src/pages/docs/desired-capabilities/geo-location-for-localization.md
- src/pages/docs/open-source-docs/docker.md
- src/pages/docs/windows-automation/import-tsrx-files.md
- Fixed pages having HTTP links and Updated agent setup doc
> Dev >>> Fixed pages having HTTP links and Updated agent setup doc

- src/left-nav-title.json
- src/pages/docs/reports/runs/custom-pdf-report.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
- src/pages/docs/test-cases/manage/features-and-scenarios.md
- src/pages/docs/windows-automation/introduction.md
Added a new doc for folder structure and updated Mobile Test Steps & Windows Adv Intro docs.
> Added a new doc for Folder Structure

- src/left-nav-title.json
- src/pages/docs/reports/runs/custom-pdf-report.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
- src/pages/docs/test-cases/manage/features-and-scenarios.md
- src/pages/docs/windows-automation/introduction.md
Added a new doc for folder structure and updated Mobile Test Steps & Windows Adv Intro docs.
> Added a new doc for Folder Structure (#518)

- src/left-nav-title.json
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/test-cases/create-steps-restapi/mock-apis.md
Updated recording single element document as per the ticket https://testsigma.atlassian.net/browse/IDEA-1363.
> Updated recording single element document 

- src/left-nav-title.json
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/troubleshooting/mobile-apps/handling-ios-app-compatibility-issues.md
Added a new troubleshooting doc for IPA file build & Added a new section under Test Data Profile for TDP Creation using Gen AI.
> Added a new troubleshooting doc for IPA file build

- src/left-nav-title.json
- src/pages/docs/continuous-integration/copado-integration.md
- src/pages/docs/continuous-integration/gearset.md
Added a new doc for Gearset CI CD as per the ticket https://testsigma.atlassian.net/browse/IDEA-1909.
> Added a new doc for Gearset Integration

- scripts/indexr.js
- src/left-nav-title.json
- src/pages/docs/continuous-integration/copado-integration.md
- src/pages/docs/continuous-integration/gearset.md
- src/pages/docs/desired-capabilities/basic-authentication-safari.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-data/types/mailbox.md
- src/pages/docs/test-data/types/phone-number.md
- src/pages/docs/testsigma-tunnel/using-tunnel.md
New docs for Gearset Integration & Basic Authentication (Safari)
> New docs for Gearset Integreation & Basic Authentication (Safari)

- src/left-nav-title.json
- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/genai-capabilities/copilot.md
- src/pages/docs/genai-capabilities/generate-tdp.md
- src/pages/docs/genai-capabilities/generate-tests-from-requirements.md
- src/pages/docs/genai-capabilities/generate-tests-from-user-actions.md
- src/pages/docs/open-source-docs/docker.md
- src/pages/docs/open-source-docs/introduction-community.md
- src/pages/docs/open-source-docs/reset-password.md
- src/pages/docs/open-source-docs/testsigma-community-cloud.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/testsigma-tunnel/intro.md
- src/pages/docs/testsigma-tunnel/key-components.md
- src/pages/docs/testsigma-tunnel/setup-installation-docker.md
- src/pages/docs/testsigma-tunnel/setup-installation-linux.md
- src/pages/docs/testsigma-tunnel/setup-installation-mac.md
- src/pages/docs/testsigma-tunnel/setup-installation-windows.md
- src/pages/docs/testsigma-tunnel/using-tunnel.md
- src/pages/docs/windows-automation/error-handling.md
- src/pages/docs/windows-automation/import-tsrx-files.md
- src/pages/docs/windows-automation/introduction.md
- src/pages/docs/windows-automation/object-learning.md
- src/pages/docs/windows-automation/project-and-application.md
- src/pages/docs/windows-automation/test-cases.md
- src/pages/docs/windows-automation/tsr-tsrx-files.md
Created new section in left nav bar and 2 new docs for GenAI Features.
> Created new section and docs for GenAI Feature

- src/left-nav-title.json
- src/pages/docs/configuration/generate-wda-file.md
- src/pages/docs/configuration/security/azure-sso.md
- src/pages/docs/configuration/security/google-sso.md
- src/pages/docs/configuration/security/okta-sso.md
- src/pages/docs/desired-capabilities/basic-authentication-safari.md
- src/pages/docs/genai-capabilities/copilot.md
- src/pages/docs/genai-capabilities/generate-tdp.md
- src/pages/docs/genai-capabilities/generate-tests-from-requirements.md
- src/pages/docs/genai-capabilities/generate-tests-from-user-actions.md
Updated Okta SSO, Gen AI, Basic Auth DC docs:
> Updated Okta SSO & Gen AI docs

- .github/workflows/cd.yml
- .github/workflows/staging-cd.yml
- Clean the cached versions on Gatsby build
> fix: Clean the cached versions on Gatsby build

- src/pages/docs/testsigma-tunnel/intro.md
- fix: removed the double slash on url
> fix: removed the double slash on url

- src/left-nav-title.json
- src/pages/docs/api/environments.md
Updated Environments API doc as per the ticket https://testsigma.atlassian.net/browse/IDEA-2041.
> Updated Environments API Document

- src/pages/docs/test-cases/manage/custom-fields.md
We have created a new doc for custom fields for test cases as per the ticket: https://testsigma.atlassian.net/browse/IDEA-1984
> Created new document for Custom Fields

- src/pages/docs/salesforce-testing/special-nlps.md
Updated Salesforce Special NLPs document with usage of Read API details as per the ticket https://testsigma.atlassian.net/browse/IDEA-1910.
> Updated Salesforce Special NLPs document

- src/left-nav-title.json
- src/pages/docs/api/environments.md
- src/pages/docs/genai-capabilities/generate-tests-from-requirements.md
- src/pages/docs/genai-capabilities/generate-tests-from-swagger.md
- src/pages/docs/genai-capabilities/generate-tests-from-user-actions.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/test-cases/manage/custom-fields.md
Updated Salesforce NLP document, added new docs for GenAI Swagger API and Custom Fields document.
> Updated SF NLP & Added GenAI Swagger API doc  

- src/left-nav-title.json
- src/pages/docs/reports/export-reports/export-report-pdf.md
- src/pages/docs/reports/export-reports/export-report-xls.md
- src/pages/docs/reports/export-reports/export-reports-junit.md
- src/pages/docs/reports/runs/custom-pdf-report.md
- src/pages/docs/reports/runs/drill-down-reports.md
- src/pages/docs/reports/runs/filter-custom-reports.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/runs/test-plan-executions.md
Updated Run Results docs as per updated UI as per the ticket https://testsigma.atlassian.net/browse/IDEA-2102.
> Updated Run Results docs as per updated UI

- src/pages/docs/elements/auto-healing.md
- src/pages/docs/elements/import-export.md
- src/pages/docs/elements/locator-precedence.md
- src/pages/docs/elements/verify-elements.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/elements/web-apps/iframe-elements.md
- src/pages/docs/elements/web-apps/image-based-elements.md
- src/pages/docs/elements/web-apps/record-multiple-elements.md
- src/pages/docs/elements/web-apps/shadow-dom.md
Added new document for image based element creation.
> New document for image based element creation

- src/pages/docs/elements/auto-healing.md
- src/pages/docs/elements/import-export.md
- src/pages/docs/elements/locator-precedence.md
- src/pages/docs/elements/verify-elements.md
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/elements/web-apps/create-manually.md
- src/pages/docs/elements/web-apps/iframe-elements.md
- src/pages/docs/elements/web-apps/image-based-elements.md
- src/pages/docs/elements/web-apps/record-multiple-elements.md
- src/pages/docs/elements/web-apps/shadow-dom.md
Added new document for image based element creation as per the ticket https://testsigma.atlassian.net/browse/IDEA-1926.
> New document for image based element creation 

- src/pages/docs/getting-started/command center.md
- src/pages/docs/projects/applications.md
- src/pages/docs/projects/overview.md
- src/pages/docs/projects/settings/requirement-types.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/projects/versions.md
Created a new documentation for Command Center as per the ticket :https://testsigma.atlassian.net/browse/IDEA-1956.
> New Document for Command Center

- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/projects/settings/requirement-types.md
- src/pages/docs/projects/settings/test-case-types.md
Updated all the screenshots and GIFs in the "Projects and Settings" section according to the new UI.
> Updated Screenshots in the "Projects and Settings" section.

- src/pages/docs/genai-capabilities/mobile-copilot-android.md
Added a new doc for Mobile Copilot as per the ticket https://testsigma.atlassian.net/browse/IDEA-2135.
> Added a new doc for Mobile Copilot

- src/pages/docs/genai-capabilities/mobile-copilot-android.md
Updated mobile copilot document as per IDEA-2135.
> Updated Mobile Copilot

- src/pages/docs/genai-capabilities/mobile-copilot.md
Implemented PM's feedback in Mobile Copilot documentation.
> Updated Mobile Copilot document as per feedback

- src/pages/docs/api/examples/rerun-test-cases-in-test-run.md
- src/pages/docs/api/examples/trigger-sf-metadata.md
- src/pages/docs/collaboration/assign-projects.md
- src/pages/docs/collaboration/elements-review-management.md
- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/collaboration/manage-execution-stops.md
- src/pages/docs/collaboration/test-cases-review-management.md
- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/genai-capabilities/generate-tests-from-swagger.md
- src/pages/docs/projects/applications.md
- src/pages/docs/projects/requirements.md
- src/pages/docs/projects/settings/requirement-types.md
- src/pages/docs/projects/settings/test-case-priorities.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/projects/versions.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/error-handling.md
- src/pages/docs/salesforce-testing/introduction.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/salesforce-testing/table-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
* Added new doc for metadata refresh using API
Added a new document for Salesforce Metadata Refresh Using API.
* Few changes
> Added new doc for metadata refresh using API (#565)

- src/left-nav-title.json
- src/pages/docs/accessibility-testing/accessibility-testing.md
- src/pages/docs/accessibility-testing/mobile-accessibility-testing.md
- src/pages/docs/reports/export-reports/export-report-pdf.md
+ New document for Mobile Accessibility Testing
Staging Link - https://website.testsigma.com/docs/accessibility-testing/mobile-accessibility-testing/
> New document for Mobile Accessibility Testing

- src/left-nav-title.json
- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/debugging/launch-the-debugger-in-the-same-window.md
- src/pages/docs/debugging/results-on-local-devices.md
- src/pages/docs/integrations/test-management/qtest.md
- src/pages/docs/live-editor/editing-test-case.md
- src/pages/docs/live-editor/faqs-on-live-editor.md
- src/pages/docs/live-editor/faqs-on-testsigma-lite.md
- src/pages/docs/live-editor/installing-testsigma-lite.md
- src/pages/docs/live-editor/intro-testsigma-lite.md
Added new docs for Testsigma Lite (Live Editor)
https://website.testsigma.com/docs/live-editor/intro-testsigma-lite/
https://website.testsigma.com/docs/live-editor/installing-testsigma-lite/
https://website.testsigma.com/docs/live-editor/editing-test-case/
https://website.testsigma.com/docs/live-editor/faqs-on-testsigma-lite/
> Added new docs for Testsigma Lite 

- src/pages/docs/collaboration/assign-projects.md
- src/pages/docs/collaboration/elements-review-management.md
- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/collaboration/manage-execution-stops.md
- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/genai-capabilities/generate-tests-from-figma-designs.md
- src/pages/docs/live-editor/faqs-on-testsigma-lite.md
- src/pages/docs/live-editor/installing-testsigma-lite.md
- src/pages/docs/projects/applications.md
- src/pages/docs/projects/overview.md
- src/pages/docs/projects/requirements.md
- src/pages/docs/projects/settings/requirement-types.md
- src/pages/docs/projects/settings/test-case-types.md
- src/pages/docs/projects/versions.md
- src/pages/docs/test-management/test-suites/dynamic-test-suites.md
I have updated the "Generate Test Cases from Figma Designs" doc as per the ticket https://testsigma.atlassian.net/browse/IDEA-2247
> Updated "Generate Test Cases from Figma Designs" doc

- src/pages/docs/collaboration/assign-projects.md
- src/pages/docs/collaboration/invite-team-members.md
- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/continuous-integration/gearset.md
- src/pages/docs/genai-capabilities/copilot.md
- src/pages/docs/genai-capabilities/generate-tests-from-requirements.md
Updated Requirements GenAI document with steps to generate  Salesforce test cases from requirements.
> Updated Requirements GenAI document (#614)

- src/pages/docs/FAQs/mobile-apps/apple-pay-automation.md
- src/pages/docs/genai-capabilities/generate-tests-from-figma-designs.md
- src/pages/docs/index.jsx
- src/pages/docs/integrations/test-management/qtest.md
- src/pages/docs/salesforce-testing/metadata-connections.md
Added a documentation for "Apple Pay Automation" as per the ticket https://testsigma.atlassian.net/browse/IDEA-2270
> Added a documentation for "Apple Pay Automation" 

- src/pages/docs/visual-testing/visual-testing-with-figma-designs.md
New doc for Visual Testing with Figma Designs.
Here's the staging link for the same https://website.testsigma.com/docs/visual-testing/visual-testing-with-figma-designs/
> New doc for Visual Testing with Figma Designs

- src/pages/docs/integrations/overview.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
Staging Link - https://website.testsigma.com/docs/test-cases/manage/add-edit-delete/#test-case----advanced-options
> Added pre-requisite execution options in test cases 

- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/runs/test-plan-executions.md
Minor updates to Users & Run Results 
Staging Links:
https://website.testsigma.com/docs/runs/test-plan-executions/
https://website.testsigma.com/docs/collaboration/users-roles/
> Minor updates to Users & Run Results

- src/components/SearchInputBox.jsx
- src/components/header.jsx
- src/templates/page.scss
- Testsigma Docs header responsiveness issue
> [Dev]: Testsigma Docs header responsiveness issue (#651)

- src/components/seo.jsx
- Updated the Docs home page title on breadcrumb schema
> Updated the Docs home page title on breadcrumb schema

- src/components/seo.jsx
- Fixed font issue on Safari -  v1
> [WEB-1691] - Fixed font issue on Safari -  v1

- src/components/seo.jsx
- [WEB-1691] - Fixed freshChat UI Issue
[WEB-1691]: https://testsigma.atlassian.net/browse/WEB-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Dev] - [WEB-1691] - Fixed freshChat UI Issue

- src/components/header.jsx
- src/pages/docs/troubleshooting/mobile-apps/app-package-and-activity.md
- src/pages/docs/troubleshooting/mobile-apps/capture-network-logs-in-android-app.md
- src/pages/docs/troubleshooting/mobile-apps/click-tap-failure.md
- src/pages/docs/troubleshooting/mobile-apps/common-android-issues.md
- src/pages/docs/troubleshooting/mobile-apps/compatible-id-locators.md
- src/pages/docs/troubleshooting/mobile-apps/developer-mode-for-ios.md
- src/pages/docs/troubleshooting/mobile-apps/disable-play-protect-for-sms-forwarder-installation.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-UI.md
- src/pages/docs/troubleshooting/mobile-apps/failed-to-launch-test-recorder.md
- src/pages/docs/troubleshooting/mobile-apps/finding-app-bundle-id-ios.md
- src/pages/docs/troubleshooting/mobile-apps/handling-ios-app-compatibility-issues.md
- src/pages/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures.md
- src/pages/docs/troubleshooting/mobile-apps/more-prerequisite-settings.md
- src/pages/docs/troubleshooting/mobile-apps/test-execution-queued-for-a-long-time.md
- src/pages/docs/troubleshooting/mobile-apps/unable-to-start-wda-process.md
- src/pages/docs/troubleshooting/mobile-apps/why-accessibility-ids-over-others.md
- src/templates/page.scss
- Added a capturing network logs in Android Doc, and fixed the Nav CTA button spacing issues
> [Dev] - Added a capturing network logs in android Doc and Fixed the Nav CTA button spacing issues

- src/components/seo.jsx
- src/left-nav-title.json
- src/pages/docs/FAQs/mobile-apps/why-am-i-facing-permission-error-during-local-test-execution.md
- src/pages/docs/continuous-integration/codemagic-ci.md
- src/pages/docs/index.jsx
- Added New FAQs and Migrated the react-helmet to gatsby's Head API
> [Dev] - Added New FAQs and Migrated the react-helmet to gatsby's Head API

- src/components/seo.jsx
> WEB-1411 - removed unwanted tag (#712)

- package.json
- src/components/seo.jsx
- Cherry picking the SEO changes
> [WEB-1411] - Cherry picking the SEO changes

- src/pages/docs/FAQs/general/how-to-handle-browser-related-pop-up-issues.md
Updated the "How to Handle Browser-Related Pop-Up Issues" doc as per the ticket https://testsigma.atlassian.net/browse/IDEA-2390
> Updated the "How to Handle Browser-Related Pop-Up Issues" doc 

- src/left-nav-title.json
- src/pages/docs/FAQs/general/why-do-errors-occur-when-i-try-to-download-files-from-the-exports-page.md
- src/pages/docs/FAQs/general/why-does-test-execution-fail-with-the-error-no-route-to-host.md
- src/pages/docs/atto/generative-ai/integrations/figma.md
- src/pages/docs/atto/generative-ai/integrations/github.md
- src/pages/docs/atto/generative-ai/integrations/jira-server.md
- src/pages/docs/atto/generative-ai/integrations/qtest.md
- src/pages/docs/atto/generative-ai/integrations/xray.md
- src/pages/docs/integrations/bug-reporting/jira.md
- src/pages/docs/live-editor/editing-test-case.md
- src/pages/docs/live-editor/faqs-on-testsigma-terminal.md
- src/pages/docs/live-editor/installing-testsigma-terminal-on-linux.md
- src/pages/docs/live-editor/installing-testsigma-terminal-on-windows.md
- src/pages/docs/test-plans/supported-test-lab-types.md
Updated the "JIRA Bug Reporting Integration" doc and added the following docs:
Integrate Jira Server/Data Center with Testsigma
Installing Testsigma Terminal on Linux
Installing Testsigma Terminal on Windows
Why do Errors Occur When I Try to Download Files from The Exports Page?
Why does Test Execution Fail with the Error No route to host?
Updated the "Test Lab Types" doc as per the ticket https://testsigma.atlassian.net/browse/DOC-346
as per the tickets https://testsigma.atlassian.net/browse/IDEA-2406, https://testsigma.atlassian.net/browse/DOC-346
> Added 5 new FAQs and updated 2 existing docs

- src/pages/docs/configuration/api-keys.md
- src/pages/docs/visual-testing/configure-test-steps.md
Added a section - "Visual Testing Mode" to the existing doc - "Visual Testing" as per the ticket https://testsigma.atlassian.net/browse/IDEA-2414
> Updated the "Visual Testing" doc 
