testsigmahq/testsigma-docs

- src/templates/page.scss
Fixed issue in safari, not able to view the images when we click on the image. The image says that its broken.
> fix: Documentation - images break when clicked to expand them

- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
This article describes the steps to troubleshoot the error _Testsigma agent not detecting local devices (Android and iOS devices) for mobile test recorder_ .
> Troubleshoot: Agent not displaying local device

- src/pages/docs/troubleshooting/NLPs/unable-to-retrieve-value.md
- src/pages/docs/troubleshooting/agent/unable-to-create-new-testsession.md
Created a new troubleshooting doc for https://testsigma.atlassian.net/browse/DOC-16
steps to debug the local mobile execution issues: troubleshoot "Unable to create a new Test Session due to unexpected failure(0x537). - Error while creating driver"
> Troubleshooting docs 3.0.0

- src/pages/docs/agent/setup-on-windows-mac-linux.md
Update the ticket's documentation for Run Testsigma Agent Using Docker: https://testsigma.atlassian.net/browse/DOC-146. 
> Updated Doc for Run Testsigma Agent using docker

- src/pages/docs/api/restful-api-testing-version-2/api-request.md
RESTful API documentation now includes Unicode; the ticket's documentation can be found at https://testsigma.atlassian.net/browse/DOC-139.
> Added Unicode in RESTful API Doc

- src/pages/docs/test-data/types/mailbox.md
The Runtime variable for store data has been included from the mailbox and subsequently updated in the mailbox test data type document for the ticket https://testsigma.atlassian.net/browse/DOC-129.
> Updated Mailbox Test data type document

- src/pages/docs/test-data/data-generators/default-list.md
- src/pages/docs/test-data/types/mailbox.md
Added Mailbox Alias to the Mailbox TDT Doc and Updated Default Test Data Generator Document for the tickets https://testsigma.atlassian.net/browse/DOC-129 and https://testsigma.atlassian.net/browse/DOC-134.
> Updated Default Data Generators, Mailbox TDT Doc

- src/pages/docs/continuous-integration/azure-devops.md
- src/pages/docs/continuous-integration/circle-ci.md
- src/pages/docs/test-cases/step-types/if-condition.md
- src/pages/docs/test-data/types/phone-number.md
Following docs are updated as per new UI:
https://testsigma.com/docs/test-cases/step-types/if-condition/
https://testsigma.com/docs/test-data/types/phone-number/
https://testsigma.com/docs/continuous-integration/circle-ci/
https://testsigma.com/docs/continuous-integration/azure-devops/
> Updated docs as per new UI features

- src/components/seo.jsx
fix: Hubspot hellobar not showing up in the docs page
> fix: Hubspot hellobar not showing up in the docs page

- src/components/seo.jsx
fix: hubspot hellobar is not showing up on the docs site
> fix: hubspot hellobar is not showing up on the docs site

- src/pages/docs/collaboration/users-roles.md
- src/pages/docs/integrations/collaboration/slack.md
- src/pages/docs/test-cases/create-steps-recorder/ios-apps/multiple-webview-hybrid-ios.md
- src/pages/docs/test-cases/create-steps-recorder/ios-apps/overview.md
- src/pages/docs/test-cases/step-types/while-loop.md
Updated the following docs as per new UI:
https://testsigma.com/docs/test-cases/step-types/while-loop/
https://testsigma.com/docs/integrations/collaboration/slack/
https://testsigma.com/docs/collaboration/users-roles/ 
https://testsigma.com/docs/test-cases/create-steps-recorder/ios-apps/multiple-webview-hybrid-ios/
https://testsigma.com/docs/test-cases/create-steps-recorder/ios-apps/overview/
> Updated the docs as per new UI

- src/pages/docs/collaboration/test-cases-review-management.md
- src/pages/docs/elements/overview.md
- src/pages/docs/test-cases/manage/list-actions.md
- src/pages/docs/test-cases/step-types/rest-api.md
- src/pages/docs/test-data/types/environment.md
- src/pages/docs/test-data/types/overview.md
- src/pages/docs/test-management/test-plans/schedule-plans.md
Following docs as per React UI - Set 3: https://testsigma.atlassian.net/browse/DOC-230
Test Data Types - https://testsigma.com/docs/test-data/types/overview/
Environment Test Data - https://testsigma.com/docs/test-data/types/environment/
Review Management for Test Cases - https://testsigma.com/docs/collaboration/test-cases-review-management/
Test Case List Actions - https://testsigma.com/docs/test-cases/manage/list-actions/
Schedule Test Plan - https://testsigma.com/docs/test-management/test-plans/schedule-plans/
Updated Element List Actions - https://testsigma.com/docs/elements/overview/
gif for the ticket https://testsigma.atlassian.net/browse/DOC-226
> Updated Documents as per React UI - Set 3

- src/pages/docs/desired-capabilities/biometric-authentication.md
Updated Biometric Authentication document as per the ticket https://testsigma.atlassian.net/browse/DOC-191. Please review.
> Updated Biometric Authentication Document.

- src/pages/docs/elements/import-export.md
- src/pages/docs/test-data/import-data-profiles.md
Updated the following docs as per new UI:
https://testsigma.com/docs/elements/import-export/
https://testsigma.com/docs/test-data/import-data-profiles/
> Updated docs as per new UI

- src/pages/docs/api/test-plans.md
- src/pages/docs/test-cases/create-steps-recorder/web-apps/overview.md
Updated the following docs as per new UI:
https://testsigma.com/docs/api/test-plans/
https://testsigma.com/docs/test-cases/create-steps-recorder/web-apps/overview/
> Updated the following docs as per new UI

- src/templates/page.jsx
- src/templates/page.scss
Fixed UI issue on table contents which is overlapping layout on docs page.
> fix: UI issue on table contents which is overlapping layout on docs page.

- src/pages/docs/agent/troubleshooting/upgrade-agent-automatically.md
- src/pages/docs/test-data/types/overview.md
- src/pages/docs/troubleshooting/mobile-apps/mobile-recorder-actions-failures.md
- src/templates/page.jsx
- src/templates/page.scss
- fix: UI issue on table contents which is overlapping layout on docs page.
- Added troubleshooting doc for agent upgrade
> Dev to main [28 Oct]

- src/pages/docs/on-premise setup/install-docker-on-uzure-infra.md
- src/pages/docs/on-premise setup/prerequisites.md
- src/pages/docs/on-premise setup/setup.md
Updated On-premise setup prerequisites document as per the ticket https://testsigma.atlassian.net/browse/DOC-270.
> Updated On-Prem Prerequisites doc

- src/pages/docs/getting-started/prerequisites-cloud.md
- src/pages/docs/integrations/test-labs/browserstack.md
Created a new doc for Prerequisites for Cloud Executions & updated BrowserStack doc with interlink as per the request.
> Created a new doc for Prerequisites for Cloud Executions

- src/pages/docs/elements/auto-healing.md
Created a new document for Auto Healing Feature in Testsigma as per the ticket https://testsigma.atlassian.net/browse/IDEA-883. Please review
> Created new document for Auto Healing

- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/test-data/types/phone-number.md
Updated Phone Number Doc with SMS Forwarder app & Use case linked to SMS Forward app.
> Updated Phone Number Doc with SMS Forward App

- src/pages/docs/troubleshooting/agent/mobile-device-not-displayed-recorder.md
Updated the error information for the failure of the Testsigma agent to detect local devices for the Mobile Test Recorder document. The associated ticket is https://testsigma.atlassian.net/browse/IDEA-996.
> Updated troubleshooting doc for Agent

- src/pages/docs/test-cases/create-test-steps/actions-and-options-recorder/multiple-webviews.md
- src/pages/docs/troubleshooting/mobile-apps/click-tap-failure.md
- src/pages/docs/troubleshooting/web-apps/issues-with-ui-Identifiers.md
Added Troubleshooting docs for UI Identifier Issues & Click/Tap NLP failures. Updated Hybrid Tests for Andoid/iOS doc with execution details.
> Added troubleshooting docs for Web & Mobile Apps

- src/pages/docs/configuration/generate-wda-file.md
Created a new doc under Configuration for creating WDA file for iOS app testing as per the ticket https://testsigma.atlassian.net/browse/IDEA-1052. Please review.
> Added a new doc for creating WDA File

- src/pages/docs/test-data/types/mailbox.md
Added a subsection in Mailbox doc for Steps to Setup Email Forward in Gmail to use and implement SMS forward app as per the ticket https://testsigma.atlassian.net/browse/IDEA-882. Please review.
> Mail forward setup added to Mailbox Automation

- src/left-nav-title.json
- src/pages/docs/test-step-recorder/install-chrome-extension.md
Updated Installing Chrome Extension Doc with steps to enable in Recorder Extension to record steps in Incognito.
> Updated Installing Chrome Extension Doc

- src/left-nav-title.json
- src/pages/docs/test-step-recorder/install-chrome-extension.md
Updated GIFs and Metas for Chrome Extension Doc.
> Updated GIFs and Metas

- src/left-nav-title.json
- src/pages/docs/test-step-recorder/install-chrome-extension.md
- src/pages/docs/test-step-recorder/install-edge-extension.md
- src/pages/docs/test-step-recorder/install-firefox-extension.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
Added a new document for Testsigma recorder extension in Edge as per the ticket https://testsigma.atlassian.net/browse/IDEA-1195.
> New doc for Recorder Extension: Edge

- src/left-nav-title.json
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/element-repos.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
1. Creating Metadata Connections 
2. Adding User Connections 
3. Test Cases for Salesforce (Manual + Live)
4. Salesforce Element Repositories
5. Intro: Testsigma Special NLPs
> Added Following Salesforce Documents

- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/create-sf-project.md
- src/pages/docs/salesforce-testing/element-repos.md
- src/pages/docs/salesforce-testing/introduction.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
Reordered the Salesforce Testsing section & added necessary interlinks in Salesforce documents.
> Added Interlinks in SF Docs & Reordered SF section

- src/pages/docs/troubleshooting/mobile-apps/app-package-and-activity.md
Added a new doc for finding App Package & App Activity (Android)
> New Doc to find App Package & Activity

- src/left-nav-title.json
- src/pages/docs/runs/adhoc-runs.md
- src/pages/docs/runs/test-locally-hosted-applications.md
- src/pages/docs/runs/test-plan-executions.md
- src/pages/docs/troubleshooting/web-apps/collecting-har-file.md
Updated Testsigma IP whitelisting doc & added a new doc for collecting HAR file to raise support tickets.
> Updated TS IP Whitelisting & New doc for HAR File

- src/pages/docs/configuration/security/azure-sso.md
- src/pages/docs/runs/test-locally-hosted-applications.md
Updated Azure SSO configuration doc as per the ticket https://testsigma.atlassian.net/browse/IDEA-891.
> Updated Azure SSO document

- src/pages/docs/agent/troubleshooting/max-sessions-for-agents.md
Added a new doc that helps understand how to specify max sessions for agents.
> Added a new doc for max sessions for agents

- src/pages/docs/test-cases/manage/add-edit-delete.md
Added test step settings for test cases document.
> Added test step settings for test cases doc

- src/left-nav-title.json
- src/pages/docs/api/examples/rerun-test-cases-in-test-run.md
- src/pages/docs/api/examples/run-the-same-test-plan-multiple-times-in-parallel.md
- src/pages/docs/api/examples/schedule-test-plan-with-API.md
- src/pages/docs/api/examples/trigger-multiple-test-plans.md
- src/pages/docs/api/examples/trigger-test-plan-wait-completion.md
- src/pages/docs/api/examples/update-test-case-results-using-API.md
- src/pages/docs/api/examples/values-of-test-data-profile.md
- src/pages/docs/api/get-project-wide-information.md
- src/pages/docs/api/test-results-at-all-levels.md
- src/pages/docs/api/upload-and-update-test-data-profile.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
Updated Test Step Settings and Added a new doc for fetching test results at all levels using APIs.
> Updated Step Settings & Added APIs for Results

- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/metadata-connections.md
Updated SF Docs as per Feedback.
> Updated Connected Apps & Metadata Connections Docs

- src/left-nav-title.json
- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/open-source-docs/docker.md
- src/pages/docs/open-source-docs/introduction-community.md
- src/pages/docs/open-source-docs/reset-password.md
- src/pages/docs/open-source-docs/testsigma-community-cloud.md
- src/pages/docs/salesforce-testing/connected-app.md
- src/pages/docs/salesforce-testing/introduction.md
- src/pages/docs/salesforce-testing/metadata-connections.md
- src/pages/docs/windows-automation/error-handling.md
- src/pages/docs/windows-automation/import-tsrx-files.md
- src/pages/docs/windows-automation/introduction.md
- src/pages/docs/windows-automation/object-learning.md
- src/pages/docs/windows-automation/project-and-application.md
- src/pages/docs/windows-automation/test-cases.md
- src/pages/docs/windows-automation/tsr-tsrx-files.md
Added initial set of documents for Windows Automation.
Introduction to Windows Automation
Creating a Windows Project
Element Learning through UFT
Converting TSR to TSRx files
Importing/Updating TSRx File into Testsigma
Building Test Cases for Windows Based Applications
Error Handling Post TSRx File Update
> Added new docs for Windows Automation

- src/pages/docs/elements/verify-elements.md
- src/pages/docs/test-cases/step-types/while-loop.md
- src/pages/docs/test-step-recorder/settings-include-exclude-attributes.md
Created a document for Verifying Elements from Test Recorder as per the ticket https://testsigma.atlassian.net/browse/IDEA-1545.
> Created a document for Verifying Elements

- src/pages/docs/getting-started/testsigma-sample-apps.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/special-nlps.md
Updated SF NLPs doc & Removed sample web app link as per the ticket https://testsigma.atlassian.net/browse/IDEA-1367.
> Updated SF NLPs doc & removed sample web app link

- src/pages/docs/elements/mobile-web-application/record-elements.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
- src/pages/docs/salesforce-testing/table-nlps.md
- src/pages/docs/salesforce-testing/user-connections.md
- src/pages/docs/test-cases/manage/add-test-cases-for-mobile-web-app.md
Added a new doc for Automating Listview Table NLPs, Parametrization of Login NLPs, & updated User connections document. Please review
> Added a new doc for automating listview table NLPs

- src/pages/docs/configuration/security/okta-sso.md
Added new section for signing in to Testsigma with SAML SSO and updated the document as per the ticket. Please review.
> Updated SAML SSO document

- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/bulk-actions.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-options.md
- src/pages/docs/test-cases/create-test-steps/actions-and-options-manual/step-settings.md
- src/pages/docs/test-cases/create-test-steps/overview.md
- src/pages/docs/test-cases/manage/add-edit-delete.md
- src/pages/docs/test-cases/manage/import-export.md
- src/pages/docs/test-cases/manage/import-from-yaml-or-git.md
- src/pages/docs/test-cases/manage/import-postman-to-testsigma.md
- src/pages/docs/test-cases/manage/list-actions.md
Added initial docs for Testsigma Copilot as subsections to existing page.
> Testsigma Copilot Documents

- src/pages/docs/debugging/debugging-localdevices-web.md
- src/pages/docs/debugging/launch-the-debugger-in-the-same-window.md
- src/pages/docs/debugging/results-on-local-devices.md
- src/pages/docs/reports/runs/custom-pdf-report.md
Added Custom PDF Report Document for the ticket https://testsigma.atlassian.net/browse/IDEA-1700.
> Added Custom PDF Report Document

- src/pages/docs/on-premise-setup/pre-installation/testsigma-on-prem-architecture.md
Added physical layout deployment diagram to On-premise architecture doc.
> Added deployment diagram to On-premise doc

- src/pages/docs/test-management/test-plans/run-tests-in-parallel.md
Updated Efficient Test Execution with Parallel Runs and Backup Devices Doc for the ticket https://testsigma.atlassian.net/browse/IDEA-1793.
> Updated Efficient Test Execution with Parallel Runs and Backup Devices Doc

- src/left-nav-title.json
- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/on-premise-setup/pre-installation/testsigma-on-prem-architecture.md
- src/pages/docs/open-source-docs/docker.md
- src/pages/docs/open-source-docs/introduction-community.md
- src/pages/docs/open-source-docs/reset-password.md
- src/pages/docs/open-source-docs/testsigma-community-cloud.md
- src/pages/docs/windows-automation/error-handling.md
- src/pages/docs/windows-automation/import-tsrx-files.md
- src/pages/docs/windows-automation/introduction.md
- src/pages/docs/windows-automation/object-learning.md
- src/pages/docs/windows-automation/project-and-application.md
- src/pages/docs/windows-automation/test-cases.md
- src/pages/docs/windows-automation/tsr-tsrx-files.md
- src/pages/docs/windows-lite-automation/element-learning.md
- src/pages/docs/windows-lite-automation/introduction.md
- src/pages/docs/windows-lite-automation/projects-and-applications.md
- src/pages/docs/windows-lite-automation/test-cases.md
Added 4 new docs for Windows Lite Apps & Updated On-premise Architecture doc.
On Prem Architecture:
> Added Windows Lite docs & updated Onprem Archi doc

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- src/pages/docs/addons/Faqs/connect-mongodb-and-postgresql-via-addon.md
- src/pages/docs/addons/community-marketplace.md
- src/pages/docs/addons/install-community-addon.md
- src/pages/docs/addons/update.md
- src/pages/docs/test-data/create-data-profiles.md
- src/pages/docs/test-management/test-plans/email-configuration.md
Updated Connect MongoDB & PostgreSQL Databases Doc
Updated Email Configuration in Test Plan Doc
Updated Install and Use Community Addons in Testsigma Doc
Updated Updating an Addon in Testsigma Doc
Updated Addons Community Marketplace Doc
Updated Create and Use Test Data Profiles Doc
> Updated Documentation for Doc Improvement

- src/pages/docs/salesforce-testing/element-repos.md
- src/pages/docs/salesforce-testing/sf-test-cases.md
Updated Salesforce Test Case & added creating elements section for SF.
> Updated Salesforce Test Case & Elements document

- src/pages/docs/salesforce-testing/special-nlps.md
An NLP is added which was missing form the document
> Updated Salesforce NLPs document

- src/left-nav-title.json
- src/pages/docs/elements/web-apps/capture-single-element.md
- src/pages/docs/test-cases/create-steps-restapi/mock-apis.md
Updated **Record Single Element Using Recorder** & Mock API docs
> Updated recording single element doc

- src/pages/docs/best-practices/best-practices.md
- src/pages/docs/open-source-docs/docker.md
- src/pages/docs/open-source-docs/introduction-community.md
- src/pages/docs/open-source-docs/reset-password.md
- src/pages/docs/open-source-docs/testsigma-community-cloud.md
- src/pages/docs/testsigma-tunnel/setup.md
Created a new section and doc for Testsigma Tunnel.
> Created a new doc for Testsigma Tunnel

- src/pages/docs/FAQs/web-apps/why-cloud-devices-cannot-access-local-apps.md
- src/pages/docs/agent/troubleshooting/setup-issues.md
- src/pages/docs/getting-started/setup/downloadable-package.md
- src/pages/docs/runs/executing-tests-in-private-grid.md
- src/pages/docs/troubleshooting/web-apps/url-not-accessible.md
Updated localhost URLs with texts as per SEO suggestions in the following pages:
https://testsigma.com/docs/runs/executing-tests-in-private-grid/ 
https://testsigma.com/docs/agent/troubleshooting/setup-issues/ 
https://testsigma.com/docs/FAQs/web-apps/why-cloud-devices-cannot-access-local-apps/ 
https://testsigma.com/docs/getting-started/setup/downloadable-package/ 
https://testsigma.com/docs/troubleshooting/web-apps/url-not-accessible/
> Updated localhost URLs in doc pages

- src/pages/docs/troubleshooting/mobile-apps/handling-ios-app-compatibility-issues.md
Updated iOS compatibility issues document as per the feedback.
> Updated iOS compatibility issues document

- scripts/indexr.js
- Fixed the issue on Docs search bar issue (Results not found for some keyword)
> Fixed the issue on Docs search bar issue (Results not found for some keyword)

- .github/workflows/cd.yml
- .github/workflows/staging-cd.yml
- Reverted "fix: Clean the cached versions on Gatsby build"
> Reverted "fix: Clean the cached versions on Gatsby build"

- src/pages/docs/genai-capabilities/generate-tests-from-requirements.md
- src/pages/docs/genai-capabilities/generate-tests-from-swagger.md
- src/pages/docs/genai-capabilities/generate-tests-from-user-actions.md
- src/pages/docs/salesforce-testing/special-nlps.md
Added a new doc for generating API Test Cases using Swagger schema.
> New doc for generating API tests using Swagger

- src/left-nav-title.json
- src/pages/docs/reports/export-reports/export-report-pdf.md
- src/pages/docs/reports/export-reports/export-report-xls.md
- src/pages/docs/reports/export-reports/export-reports-junit.md
- src/pages/docs/reports/runs/custom-pdf-report.md
- src/pages/docs/reports/runs/drill-down-reports.md
- src/pages/docs/reports/runs/filter-custom-reports.md
- src/pages/docs/reports/runs/overview.md
- src/pages/docs/runs/test-plan-executions.md
Updated Run Results docs as per updated UI as per the ticket https://testsigma.atlassian.net/browse/IDEA-2102.
> Updated Run Results docs as per updated UI

- src/pages/docs/api/examples/manage-test-steps-api.md
- Added new doc `test-steps-api.md` covering test step management using APIs
- Documented endpoints for:
- Create test step
- Retrieve test steps
- Update test step
- Delete test step
- Included request type, endpoint, parameters, request/response body, and examples
> Added API documentation for managing test steps
